### ISSUE TITLE
Add summaries to existing collections in staging

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#102]
Acceptance criteria: All STAC collections https://staging-stac.delta-backend.xyz/collections in staging have summaries with datetime and cog_default min/max/average values

This looks pretty straightforward: https://github.com/NASA-IMPACT/delta-backend/issues/31#issuecomment-1067384301

cc @anayeaye

**Comment by abarciauskas-bgse** [comment]
@anayeaye those files I believe represent an annual datasets so I believe all the COGs each represent one year from 2005 to 2021, should the datetimes or other metadata be represented differently to make this more clear?

Looking at https://staging-stac.delta-backend.xyz/collections/OMI_trno2-COG/items?limit=100 and https://staging-stac.delta-backend.xyz/collections/OMSO2PCA-COG/items?limit=100

**Comment by anayeaye** [comment]
@abarciauskas-bgse - sorry about that, I was seeing that the month and date were the same but didn't notice that the range was across years. I think I already knew that, too. 🤦‍♀️ 

| collection | dynamic item datetime summaries | collection temporal range |
| -- | -- | -- |
| OMI_trno2-COG | `["2005-03-11T00:00:00Z", "2021-03-11T00:00:00Z"]` | `["2005-01-01T00:00:00Z", "2021-01-01T00:00:00Z"]` |
| OMSO2PCA-COG | `["2005-03-11T00:00:00Z", "2021-03-11T00:00:00Z"]` | `["2005-01-01T00:00:00Z", "2021-01-01T00:00:00Z"]` |

**Comment by slesaad** [comment]
closing as completed
