### ISSUE TITLE
Identify ARCO datasets for Landcover area of V0 climate dashboard

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#105]
[Direction given in Trilateral Dataset list](https://docs.google.com/spreadsheets/d/1WvwifHCN44fntlUKPDBMkfzpvrGQcbyMsBCFtn7Pu1M/edit#gid=1098798450)

- [ ] Propose initial dataset(s) for thematic area climate dashboard
- [ ] Check with Manil and team
- [ ] Identify data experts who will validate COG for those datasets

**Comment by slesaad** [comment]
stale
