### ISSUE TITLE
Add a Ocean NPP dataset to the API (high-level steps)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#110]
For each dataset, we will follow the following steps:

## Identify the dataset and what the processing needs are
1. Identify dataset and where it will be accessed from. Check it's a good source with science team. Ask about specific variables and required spatial and temporal extent. Note most datasets will require back processing (e.g. generating cloud-optimized data for historical data).
2. If the dataset is ongoing (i.e. new files are continuously added and should be included in the dashboard), design and construct the forward-processing workflow. 
    - Each collection will have a workflow which includes discovering data files from the source, generating the cloud-optimized versions of the data and writing STAC metadata.
   - Each collection will have different requirements for both the generation and scheduling of these steps, so a design step much be included for each new collection / data layer.
3. If appropriate, create COG conversion code and verify the COG output with a data product expert (for example, someone at the DAAC which hosts the native format) by sharing in a visual interface.

## Design the metadata and publish to the Dev API

1. Review conventions for generating STAC collection and item metadata:
   - Collections: https://github.com/NASA-IMPACT/delta-backend/issues/29 and STAC version 1.0 specification for collections
   - Items: https://github.com/NASA-IMPACT/delta-backend/issues/28 and STAC version 1.0 specification for items
   - NOTE: The delta-backend instructions are specific to datasets for the climate dashboard, however not all datasets are going to be a part of the visual layers for the dashboard so I believe you can ignore the instructions that are specific to "dashboard" extension, "item_assets" in the collection and "cog_default" asset type in the item
  
2. After reviewing the STAC documentation for collections and items and reviewing existing scripts for generating collection metadata (generally with SQL) and item metadata, generate or reuse scripts for your collection and a few items to publish to the testing API. There is some documentation and examples for how to generate a pipeline or otherwise document your dataset workflow in https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines. We would like to maintain the scripts folks are using to publish datasets in that repo so we can easily re-run those datasets ingest and publish workflows if necessary.

3.  If necessary, request access and credentials to the dev database and ingest and publish to the Dev API. Submit a PR with the manual or CDK scripts used to run the workflow to publish to the Dev API and include links to the published datasets in the Dev API

## Publish to the Staging API

Once the PR is approved, we can merge and publish those datasets to the Staging API

**Comment by abarciauskas-bgse** [comment]
I started working on the script here: https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/ab/ocean-npp/dataset-workflows/ocean-npp/test-conversion.sh using files Laura Lorenzini sent over email.

She also provided the following color palette: 
[pallet.txt](https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/files/8375827/pallet.txt)

Which I think we can use to generate a custom color map using the code Zach Frachnact provided:

```python
from matplotlib.colors import LinearSegmentedColormap
import numpy as np
colors = (np.loadtxt('pallet.txt')/255.)
cmap = LinearSegmentedColormap.from_list('Data',colors,N=200)
cmap.set_over(tuple(colors[-1]))
cmap.set_under(tuple(colors[0]))
```

but I haven't tried it yet. Jeevan used that code to generate a custom colormap we used for NO2 and SO2 datasets, see this example: https://github.com/NASA-IMPACT/delta-dashboard-datasets/blob/main/datasets/OMSO2PCA.json#L16

**Comment by abarciauskas-bgse** [comment]
The .nc files can be accessed with URS

I used:
```
curl -O -b ~/.urs_cookies -c ~/.urs_cookies -L -n <HTTPS_URL>
```

Where `<HTTPS_URL>` was one of:
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20200012020031.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20200322020060.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20200612020091.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20200922020121.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20201222020152.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20201532020182.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20201832020213.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20202142020244.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20202452020274.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20202752020305.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20203062020335.L3m_MO_NPP_npp_vgpm_4km.nc
https://oceandata.sci.gsfc.nasa.gov/ob/getfile/A20203362020366.L3m_MO_NPP_npp_vgpm_4km.nc

The pipeline should either get those files directly and create the COG OR we can upload them to s3://climatedashboard-data/delivery/MO_NPP_npp_vgpm/ and create a pipeline from there. It will reduce total storage and transfer to have the pipeline fetch and process the NetCDFs from oceandata.sci.gsfc.nasa.gov

**Comment by xhagrg** [comment]
Created a new collection called `MO_NPP_npp_vgpm`. The items are published to https://staging-stac.delta-backend.xyz/collections/MO_NPP_npp_vgpm/items . The details are not proper for the collection. Waiting for reply from SMEs. @abarciauskas-bgse can you help validate the ingestion?

**Comment by abarciauskas-bgse** [comment]
LGTM @xhagrg - is there a reason we skipped ingesting to DEV? I think the process should typically ingest to DEV first, validate and then ingest to STAGING.

**Comment by xhagrg** [comment]
DEV is under maintenance (refactoring) and Staging was functional. So, just pushed to staging. Once the refactor is done, we will follow the dev->staging process.

**Comment by abarciauskas-bgse** [comment]
Cool!

**Comment by abarciauskas-bgse** [comment]
@xhagrg just noticed that the published location is in the "delivery/" subdirectory - could we move these files into their own directory at the root of the bucket? I see the first item is at "s3://climatedashboard-data/delivery/MO_NPP_npp_vgpm/A_202012.L3m_MO_NPP_npp_vgpm_4km.tif" and I think it should be "s3://climatedashboard-data/MO_NPP_npp_vgpm/A_202012.L3m_MO_NPP_npp_vgpm_4km.tif"

**Comment by xhagrg** [comment]
consider it done.

**Comment by abarciauskas-bgse** [comment]
From Sean Bailey:
>As Laura noted, these products are still preliminary.  A draft of the product documentation page can be found here: https://oceancolor.gsfc.nasa.gov/atbd/npp/
>
>The product we’re producing at OBPG is based on the product made available by the Oregon State Ocean Primary Productivity site: http://sites.science.oregonstate.edu/ocean.productivity/standard.product.php

Perhaps for the description we should link to the https://oceancolor.gsfc.nasa.gov/atbd/npp/ page, I'll ask Sean

**Comment by abarciauskas-bgse** [comment]
@xhagrg I think this can be closed, if the descriptions have been updated?

**Comment by xhagrg** [comment]
Sounds good. Will do that today.

**Comment by xhagrg** [comment]
@abarciauskas-bgse check https://staging-stac.delta-backend.xyz/collections/MO_NPP_npp_vgpm/

**Comment by slesaad** [comment]
the dataset exists in the veda stac APi, so closing this!
