### ISSUE TITLE
Architecture: Backfilling HLS L30 and S30 metadata

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#120]
Acceptance criteria:
- Estimate (and document method of estimation) of the time and resources required to backfill metadata for all HLS L30 and S30 products.

Proposed process:
- Perform a 1% test to estimate time + resources
- List any potential bottlenecks and design CMR batches and limit increases (such as to memory and queueing) to address those bottlenecks
- Design adjustments to the pipeline to address those bottlenecks: I assume we will have to do some batching of our CMR query to do the backfilling otherwise we will reach memory limits trying to list and create metadata for all the items.
- We should expect to batch around AWS limits and limits to pgSTAC bulk loading.

Proposal to create estimate: Create a "1%" to create a time and resource consumption estimate: @slesaad since you did a small subset ingest for the hurricanes in https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/issues/95 perhaps you could say how much time and what resources that subset took. However, this was a _very_ small subset, percentage wise so we may want to come up with a more substantial 1% test. 2,638 S30 items only represents 0.079% of the S30 collection which currently has nearly 3.3 million items. (L30 is even smaller at 182 out of over 7.7 million items

Determine bottlenecks and adjust configuration workflow based on those bottlenecks: Based on the current step function workflow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/dataset-workflows/hls-cdk/cdk/cdk_stack.py what limits could we reach? Definitely memory limits of the CMR discovery function, if too many items are returned from the CMR query. Where else could we hit memory limits, queue limits, or database limits?

What is a reasonable limit to the number of items can be put in an ndjson file and loaded into pgSTAC? Perhaps @sharkinsspatial or @bitner have experience with reasonable limits for the number of items to be put in an ndjson and pgSTAC bulk load

Things we can tune:
* How many items are returned by the CMR queries we pass to the start of the step function
* Search for "memory", "max" or "batch" in our stack configuration https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/dataset-workflows/hls-cdk/cdk/cdk_stack.py

**Comment by abarciauskas-bgse** [comment]
I'm wondering if we should time box this estimate or punt it to Sprint 8 to finish datasets to be ingested for the first release. @slesaad what do you think?

**Comment by slesaad** [comment]
@abarciauskas-bgse Let's move this to Sprint 8. I'm also working on refactoring and creating a generic pipeline.

**Comment by abarciauskas-bgse** [comment]
Done

**Comment by gadomski** [comment]
Closing as OBE since it's really old and we're sunsetting this repo: https://github.com/NASA-IMPACT/veda-architecture/issues/322. Please re-open and transfer to a new repo if this is still a valid issue.
