### ISSUE TITLE
[Exploration / WIP Ticket] Convert MERRA-2 to Zarr

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#139]
## Description
As part of VEDA's support of EIS applications, Max Stevens is using MERRA-2. From our email conversation:

Max is trying to create a script on MAAP to run the CFM using my subsetted MERRA-2 data but had to move to using a pandas data frame [more details omitted]

Aimee suggested creating a Zarr archive for VEDA to allow substted access without limitations of trying to upload a zarr archive to MAAP.

Max: having MERRA-2 accessible from MAAP would be key to meeting our science objectives... serve MERRA-2 in a zarr sounds good ... we should be strategic so that we don't start serving customized subsets (e.g. geographic) of MERRA-2 for every user, which would probably end in a lot of replication. I use fields from: 

tavg1_2d_slv_Nx (M2T1NXSLV): Single-Level Diagnostics
tavg1_2d_rad_Nx (M2T1NXRAD): Radiation Diagnostics 
tavg1_2d_flx_Nx (M2T1NXFLX): Surface Flux Diagnostics 
tavg1_2d_int_Nx (M2T1NXINT): Vertically Integrated Diagnostics

but other folks in EIS might use different ones. 

### Acceptance Criteria:

- [ ] Criteria 1
- [ ] Criteria 2

## Checklist:

- [ ] Epic Link
- [ ] Detailed description
- [ ] Concept diagrams
- [ ] Assignee

**Comment by gadomski** [comment]
Closing as wontfix due to incomplete AC and the fact we're sunsetting this repo: https://github.com/NASA-IMPACT/veda-architecture/issues/322. Please re-open and transfer to another repo if this issue is still valid.
