### ISSUE TITLE
Create sample IMERG COGs for ADC Team

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#148]
## Description
Goal of this ticket is to help the ADC team with the COGs generation for IMERG. It is intended to be the first step of initial creation and handing off the the ADC team for validation. A future ticket will handle actual ingestion of the dataset.

## Acceptance Criteria

- [x] Create a valid COG using IMERG data
- [x] Document any code used
- [x] Share it with the ADC team

**Comment by aboydnw** [comment]
@abarciauskas-bgse @slesaad is this already complete? I see it marked as In Progress, but is also out of the current sprint. I feel like I had seen/heard that we sent this over to ADC to review already, but may be wrong.

cc @michaelgsuttles
