### ISSUE TITLE
Create sample LIS COG and share with freshwater team

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#149]
Acceptance criteria:
- [x] Create a valid COG using the [sample](https://drive.google.com/file/d/1i8-hEa2jl4E36TK78fIMUMvh_RHKOR-T/view?usp=sharing) Brendan shared
- [x] Document any code used
- [x] Share it with the freshwater team

Brendan a repo that he put together that contains a very basic Python script for converting LIS outputs to COG: https://github.com/bmcandr/lis_to_cog

(From Brendan's email):
The script, lis_to_cog.py, has two conversion functions. The first, to_cog(), simply uses rioxarray’s to_raster() function with the COG driver. The second, to_cog_v2(), follows the pattern in the [cogify/handler.py](https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/lambdas/cogify/handler.py) script of the NASA-IMPACT/cloud-optimized-data-pipelines repo and uses rasterio and rio-cogeo. The latter approach resulted in the data being inverted along the y-axis and the reprojection didn’t look quite right, but the first approach does not allow for much configuration of the resulting COG structure

**Comment by slesaad** [comment]
The code is documented in the gist here: https://gist.github.com/slesaad/3551de70b9243e336d267964fd192e83
