### ISSUE TITLE
Prototype UI and API for converting NetCDF or HDF5 to COG (raster-uploader)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#150]
Acceptance criteria:
- [ ] As a user, when I navigate to the UI for this service, and I upload a NetCDF or HDF5 (proposed to use GPM IMERG HHE product to start), then I can create a COG that is uploaded to S3.
- [ ] The code is documented and can be re-deployed by another developer.
- [ ] The code is in the NASA-IMPACT organization
- [ ] The code is shared with the team and they are able to understand it and provide feedback.
- [ ] The UI is demoed to management and the team.

**Comment by abarciauskas-bgse** [comment]
Noting the current code is at https://github.com/developmentseed/raster-uploader

**Comment by gadomski** [comment]
This has been moved to Done on the project board, so closing issue.
