### ISSUE TITLE
Solicit external feedback on raster-uploader

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#151]
Acceptance criteria:
- [x] Get someone from the VEDA internal team (that is not Aimee or Nick) to use raster-uploader and provide feedback
- [x] Create issues to address feedback

**Comment by abarciauskas-bgse** [comment]
@slesaad I understand you tested raster-uploader.com - did you have feedback we can incorporate into tickets?

**Comment by abarciauskas-bgse** [comment]
I'm going to close this since Slesa verbally indicated that Nick addressed some comments she made. @slesaad if you have time to note what suggestions you made that Nick addressed that would be cool.

**Comment by slesaad** [comment]
Suggestions made + addressed:
- An ability to continue from any point of processing of a file, without having to upload a new file
- Addition of a base map layer to be able to better visualize the converted COG
