### ISSUE TITLE
Discover data from S3 using recursive and regex file matching

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#158]
This is low priority at the moment, but S3 discovery should be able to use regex matching (I don't think it does already) and searching recursively into subdirectories so that users can define which files should be published in an S3 location with other files or complex file paths.

### Acceptance Criteria:

- [ ] Criteria 1
- [ ] Criteria 2

## Checklist:

- [ ] Epic Link
- [ ] Detailed description
- [ ] Concept diagrams
- [ ] Assignee

**Comment by aboydnw** [comment]
Closing because the capabilities are already in place, according to backlog refinement on 9/7
