### ISSUE TITLE
Design Workflows API

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-data-pipelines#159]
# Detail
Design "Workflows API" - an api that can be used to trigger data ingestion and publication
This will be an API on top of the existing `veda-data-pipelines`

# Acceptance Criteria
- [x] A design document outlining the API endpoints and infrastructure and how they interact with the pipeline

# Ref
[Proposal for VEDA Publication Process V1](https://docs.google.com/document/d/1RT-m8RKB2OKMdRlOu3gd0Wd0oTo_L-VHkQnsPtqLbPo/edit#heading=h.47nvlrgwummq)

**Comment by slesaad** [comment]
Here's the [design document](https://docs.google.com/document/d/1vgUGMx3R8UWVM5Ha2JtDxduaaTc1WWRxWcffBx9XDxk/edit#) for the Workflows API

**Comment by abarciauskas-bgse** [comment]
Kudos @slesaad for getting this out so quickly and @alukach for the speedy review (although you are on vacation 🤔 )
