### ISSUE TITLE
Design Domain API Mapping

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-data-pipelines#161]
## Description
Based on work done in this ticket: https://github.com/NASA-IMPACT/veda-data-pipelines/issues/168
This should be deployed to MCP so it can be accessible by users/stakeholders

## Acceptance Criteria
1. There needs to be a place for all of our services to live, and then a way for our services to be served from that path
2. Create tickets needed to implement across all backend services

**Comment by aboydnw** [comment]
We don't have to deploy to a nasa.gov url for now, since our main users will be the team and EIS users. At a later point, we may want to deploy to a nasa.gov url. This point might be when we expand to a larger user base than just EIS users. If we do switch to a nasa.gov url, we should make that change across all of our APIs.

**Comment by j08lue** [comment]
Superseded by https://github.com/NASA-IMPACT/veda-backend/issues/123
