### ISSUE TITLE
VEDA Data Pipelines should be able to publish records to the pgSTAC 0.6

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#162]
## Motivation

The pgSTAC database is actively being upgraded to pgSTAC 0.6. In order to publish records to the updated database + API, VEDA data pipelines should call a service to publish records to the upgraded database.

## Details

veda-data-pipelines is currently using pypgstac 0.4.5 https://github.com/NASA-IMPACT/veda-data-pipelines/blob/main/lambdas/db-write/requirements.txt#L4, we want to use the latest version of pypgstac https://github.com/stac-utils/pgstac/tree/v0.6.4/pypgstac.

We should update the codebase and test against a sample collection and sample item (GPM IMERG COGs or EPA Emissions COGs would be good test cases)

## Acceptance Criteria

- [ ] running veda data pipelines against a pgSTAC 0.6 database can successfully insert a collection to that database
- [ ] running veda data pipelines against a pgSTAC 0.6 database successfully inserts an item to that database
- [ ] As @alukach pointed out, this should use veda-stac-ingestor so that database insertions do not get throttled.

**Comment by alukach** [comment]
I've created #165 to track the concept of using the STAC ingestor rather than upgrading to pgSTAC 0.6

**Comment by abarciauskas-bgse** [comment]
I think I'm going to close this as a dupe of #165 unless you disagree @alukach
