### ISSUE TITLE
Publish existing 0.4.5 STAC collections and items to 0.6.6 backend

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#174]

**Comment by anayeaye** [comment]
UPDATE: I have migrated all of the collection records from our staging database into our new pgstac v0.6.6 backend because creating collections through the [veda-stac-ingestor is still under development](https://github.com/NASA-IMPACT/veda-stac-ingestor/issues/8).

**Comment by anayeaye** [comment]
This is likely replaced by #178 and #179, I will double check and close if appropriate

**Comment by anayeaye** [comment]
Confirmed, the next leg of work to ingest our existing item metadata into a pgstac v0.6.6 backend is happening in #178.
