### ISSUE TITLE
Publish all datasets to the upgraded v0.6.6 dev stac api

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data-pipelines#178]
As part of the plan to move to a newer version of pgSTAC, we need to migrate all the datasets that exist in the current staging api to a dev version of the new api.

This involves running the data pipelines for each of the collections to publish these to the new api.

**Comment by anayeaye** [comment]
This spreadsheet is a copy of export of the current/legacy collections ingested. I added a workflows column: https://docs.google.com/spreadsheets/d/1LNY3X31oJkEGxGIXelC87j8q3bJyIifcIk41aZOjrIY/edit#gid=773624342

**Comment by moradology** [comment]
Encountered a serialization issue w/ DynamoDB and Python relating to their different handling of non-integral numbers. @slesaad and @alukach helped me pin down what was going wrong and deployed the fix. Once that was in place, all ingests went off without a hitch

**Comment by slesaad** [comment]
All the data is now in https://dev-stac.delta-backend.com/. This is to be our new staging api. The spreadsheet above has the item counts matched.
