### ISSUE TITLE
Publish all datasets to the upgraded staging stac api

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data-pipelines#179]
Depends on the completion of #163.

After all the datasets are published to the new dev stac api, run the workflows again to publish them to the staging stac api.

**Comment by alukach** [comment]
Based on a team discussion, closing this ticket should also close https://github.com/NASA-IMPACT/veda-data-pipelines/issues/155

**Comment by aboydnw** [comment]
Closing as not needed in favor of #178
