### ISSUE TITLE
Ingest CO2 dataset & configure content

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/veda-data-pipelines#180]
## Description
EIS GHG would like to use CO2 for their initial stories. For the public release, these are also the priority datasets for the EIS GHG group.

## Acceptance Criteria
- [x] CO2 Diff and Mean datasets are ingested into VEDA
- [x] CO2 Diff and Mean datasets are configured to appear in the EIS thematic area on the VEDA Dashboard, with content and configurations to match the trilateral dashboard: https://eodashboard.org/explore?poi=W4-N2

**Comment by slesaad** [comment]
The CO2 diff and mean datasets have been ingested into VEDA
They currently live here:
https://dev-stac.delta-backend.com/collections/co2-diff
https://dev-stac.delta-backend.com/collections/co2-diff

(this is going to be our new staging stac api)
