### ISSUE TITLE
Integration testing to ensure that the DB represents all items in S3

### ISSUE THREAD

**Issue by moradology** [NASA-IMPACT/veda-data-pipelines#186]
Given that we have version control on all inputs to step functions/lambdas which define ingests, it should be possible to write a small integration test which verifies all imagery loaded to S3 is reflected in the database.

**Comment by gadomski** [comment]
@moradology can you comment on whether this issue is still valid for **veda-data-airflow**?

**Comment by moradology** [comment]
I believe that it is. Moving it over
