### ISSUE TITLE
Update or remove bad LIS TWS Monthly anomaly data

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data-pipelines#192]
## What
There were some data processing issues in the early production of the default cog assets for the monthly TWS anomaly dataset.
All the data < 2002-09-01 need to be re-processed and re-ingested, some files are too small (no data values) and some dates appear to be missing. If the data cannot be reprocessed the empty COGs and STAC records referring to the empty COGs should be removed.

![early-tws-anomaly-need-reprocessing](https://user-images.githubusercontent.com/3386265/190518329-0fa3ef68-0ace-4fba-be0c-c9db7cc39a61.png)

### Collection
`lis-tws-anomaly`

## Why
When a user navigates to the dashboard explore view for the `lis-tws-anomaly` dataset, the map appears broken. In fact the map is properly rendering the underlying COG which has 0 data values. 

## AC
- [x] EIS contacted for reprocessing
- [ ] Reprocessed datasets are ingested into STAC, or, if data will not be reprocessed, bad records are removed
- [ ] The EIS > TWS Anomaly Dataset > Explore page loads data on map for the first default date

# Related to 
#144

**Comment by anayeaye** [comment]
@slesaad requested these data be re-processed 2022-09-16 but we don't have a reply yet. I think we should remove the STAC records for the empty/nodata files and we can open a new ingest ticket if the bad data are replaced.

**Comment by anayeaye** [comment]
#210

**Comment by anayeaye** [comment]
I've removed the invalid lis-tws-anomaly assets and records and the explore view in the dashboard now loads data on the first available date which resolves this issue but we may decide to further prune the collection records as per #228.

**Correcting database records**
```
-- confirm selection
SELECT *
FROM items 
WHERE collection = 'lis-tws-anomaly' AND
datetime < '2002-09-01T00:00:00+00:00'
ORDER BY datetime;

--remove bad dates
DELETE FROM items 
WHERE collection = 'lis-tws-anomaly' AND
datetime < '2002-09-01T00:00:00+00:00';

-- update collection extents
UPDATE collections SET
    content = content ||
    jsonb_build_object(
        'extent', jsonb_build_object(
            'spatial', jsonb_build_object(
                'bbox', collection_bbox(collections.id)
            ),
            'temporal', jsonb_build_object(
                'interval', collection_temporal_extent(collections.id)
            )
        )
    )
WHERE collections.id='lis-tws-anomaly';

-- update summaries for dashboard
SELECT dashboard.update_collection_default_summaries('lis-tws-anomaly');
```
155 items are selected, then removed
After updating summaries and extent https://dev-stac.delta-backend.com/collections/lis-tws-anomaly checks out and a demo delta-ui running against the dev API looks good. 

Repeated in staging database, confirmed selection and equivalent count.

**Correcting S3**
I'm removing the invalid S3 objects so that future automated ingests will generate new records for the invalid data. After carefully reviewing the selection by date and file size I deleted the invalid assets from veda-data-store-staging.

**Trimming bad 2021 records**
After going through the process to remove the invalid records first uploaded for this collection, I realized that the most recent records are also invalid (after reviewing #228). I will repeat the process above to trim 2021-12-02:2021-12-31. There is not an explanation for why the latest records are invalid but the invalid December 2021 dates are the only results in this query so it may be the last of the 'empty' assets:
```
select * from items 
where collection = 'lis-tws-anomaly' and 
(items."content"->'assets'->'cog_default'->'raster:bands'-> 0 ->'statistics'->>'minimum')::float = 0 and 
(items."content"->'assets'->'cog_default'->'raster:bands'-> 0 ->'statistics'->>'maximum')::float = 0
order by datetime
limit 100;
```

**Comment by j08lue** [comment]
Great, I can see the dashboard now shows valid data from the beginning: https://www.earthdata.nasa.gov/dashboard/eis/datasets/tws-anomaly/explore

Can we somehow automate the detection of these invalid files during ingestion? What characterizes these files?

**Comment by anayeaye** [comment]
@j08lue that would be awesome. In this case, the raster min and max were both 0. I think it would be safe to use that as a test in the veda-stac-ingestor validations for all datasets--the item metadata for all default_cog assets includes raster statistics. I'm not sure about how we'd do it offhand, but a similar test we might want to do is check that all pixels are not == the no data value.

**Comment by anayeaye** [comment]
I'm closing this issue and requesting final QA in #210
