### ISSUE TITLE
Audit/fix no2-monthly* item assets

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data-pipelines#193]
# What
There are more no2-monthly item records (166) than assets in the s3 data store (154).

```
curl -X 'GET' \
  'https://staging-stac.delta-backend.com/search?collections=no2-monthly&limit=10' \
  -H 'accept: application/geo+json' | jq .context
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19823  100 19823    0     0  42447      0 --:--:-- --:--:-- --:--:-- 42447
{
  "limit": 10,
  "matched": 166,
  "returned": 10
}
```

```
aws s3 ls s3://veda-data-store-staging/no2-monthly/ --recursive --summarize | grep "Total Objects:"
Total Objects: 154
```

This minor issue does not appear to be causing any problems with the dashboard but there could be items with assets that do not exist or duplicate records for the same assets--either of which could cause unexpected behavior in either the raster tiler or in time series analyses.

# AC
- [x] no2-monthly item records agree with s3 COG assets

**Comment by anayeaye** [comment]
@danielfdsilva found some duplicate records in this collection, it looks like we may be able to identify our duplicate records based on the ID pattern

> Noticed something weird in the data that I’d like help understanding.
The [no2-monthly](https://staging-stac.delta-backend.com/collections/no2-monthly/items) dataset includes “repeated” dates.
One includes the tz and the other one doesn’t. (May be problematic in certain dashboard parts)
The id is different OMI_trno2_monthly_0.10x0.[10_202205_Col3_V4.nc](http://10_202205_col3_v4.nc/) vs OMI_trno2_0.10x0.[10_202205_Col3_V4.nc](http://10_202205_col3_v4.nc/).
Is this expected?

![no2-duplicates](https://user-images.githubusercontent.com/3386265/191545644-b25f5538-20b2-436a-9b9f-72ce3b11114f.png)

**Comment by anayeaye** [comment]
Also noted by EOX team:

> hello 
[@Alexandra Kirk](https://developmentseed.slack.com/team/U01UP0K5WJF)
 hello 
[@leo](https://developmentseed.slack.com/team/U013EMGU1D5)
 thanks for the heads up. Apart from some minor date format changes it seems the transition was fine.
There seems to be an issue though with the no2-monthly collection
 https://staging-stac.delta-backend.com/collections/no2-monthly/items
It seems requesting this collection somehow also returns entries of the no2-monthly-diff collection.
Although it seems somehow strangely mixed, for example following entry:
```
{
      "id": "OMI_trno2_0.10x0.10_202105_Col3_V4.nc",
      "bbox": [
        -180.0,
        -90.0,
        180.0,
        90.0
      ],
      "type": "Feature",
      "links": [
        {
          "rel": "collection",
          "type": "application/json",
          "href": "https://staging-stac.delta-backend.com/collections/no2-monthly"
        },
        {
          "rel": "parent",
          "type": "application/json",
          "href": "https://staging-stac.delta-backend.com/collections/no2-monthly"
        },
        {
          "rel": "root",
          "type": "application/json",
          "href": "https://staging-stac.delta-backend.com/"
        },
        {
          "rel": "self",
          "type": "application/geo+json",
          "href": "https://staging-stac.delta-backend.com/collections/no2-monthly/items/OMI_trno2_0.10x0.10_202105_Col3_V4.nc"
        }
      ],
      "assets": {
        "cog_default": {
          "href": "s3://veda-data-store-staging/no2-monthly-diff/OMI_trno2_0.10x0.10_202105_Col3_V4.nc.tif",
          "type": "image/tiff; application=geotiff; profile=cloud-optimized",
```
> shows as source `"href": "https://staging-stac.delta-backend.com/collections/no2-monthly/items/OMI_trno2_0.10x0.10_202105_Col3_V4.nc"`
but the cog_default in the assets point to :
```
"cog_default": {
          "href": "s3://veda-data-store-staging/no2-monthly-diff/OMI_trno2_0.10x0.10_202105_Col3_V4.nc.tif",
--> no2-monthly-diff
```
> So we can't really separate what is from what collection and is creating issues

**Comment by anayeaye** [comment]
Some additional notes:
1. It looks like we can use the old covid-eo-data bucket as the source of 'truth'
2. we have collaborators actively updating the no2-monthly (OMNO2d_HRM) and no2-monthly-diff (OMNO2d_HRMDifference) datasets in the covid-do-data bucket
3. 2 no2-monthly-diff datasets have been accidentally stored in the no2-monthly bucket, we should move or remove these
4. many no2-monthly-diff datasets are duplicated in the veda-data-store-staging no2-monthly bucket, these need to be identified and removed or moved (asset name does not include _monthly_)
5. there are new no2-monthly and no2-monthly-diff assets that have not been copied to the veda-data-store-staging bucket

**S3 summaries for reference**
```
no2-monthly
% aws s3 ls s3://veda-data-store-staging/no2-monthly/ --recursive --summarize | grep "Total Objects:" 
Total Objects: 154
% aws s3 ls s3://covid-eo-data/OMNO2d_HRM/ --recursive --summarize | grep "Total Objects:"
Total Objects: 81


no2-monthly-diff
% aws s3 ls s3://veda-data-store-staging/no2-monthly-diff/ --recursive --summarize | grep "Total Objects:"             
Total Objects: 89
% aws s3 ls s3://covid-eo-data/OMNO2d_HRMDifference --recursive --summarize | grep "Total Objects:"
Total Objects: 91
```

**Comment by anayeaye** [comment]
I moved the two differently named no2-monthly files to an alternate bucket to see if the different file naming pattern could have been causing a different bug that EOX is experiencing but saw no change. After testing the endpoint I moved differently named files back.
```
% aws s3 cp s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_0.10x0.10_202206_Col3_V4.nc.tif s3://covid-eo-data/OMNO2d_HRM-no2-monthly-or-diff/OMI_trno2_0.10x0.10_202206_Col3_V4.nc.tif 
copy: s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_0.10x0.10_202206_Col3_V4.nc.tif to s3://covid-eo-data/OMNO2d_HRM-no2-monthly-or-diff/OMI_trno2_0.10x0.10_202206_Col3_V4.nc.tif
% aws s3 cp s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_0.10x0.10_202207_Col3_V4.nc.tif s3://covid-eo-data/OMNO2d_HRM-no2-monthly-or-diff/OMI_trno2_0.10x0.10_202207_Col3_V4.nc.tif
copy: s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_0.10x0.10_202207_Col3_V4.nc.tif to s3://covid-eo-data/OMNO2d_HRM-no2-monthly-or-diff/OMI_trno2_0.10x0.10_202207_Col3_V4.nc.tif

% aws s3 cp s3://covid-eo-data/OMNO2d_HRM-no2-monthly-or-diff/OMI_trno2_0.10x0.10_202206_Col3_V4.nc.tif s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_0.10x0.10_202206_Col3_V4.nc.tif
copy: s3://covid-eo-data/OMNO2d_HRM-no2-monthly-or-diff/OMI_trno2_0.10x0.10_202206_Col3_V4.nc.tif to s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_0.10x0.10_202206_Col3_V4.nc.tif
% aws s3 cp s3://covid-eo-data/OMNO2d_HRM-no2-monthly-or-diff/OMI_trno2_0.10x0.10_202207_Col3_V4.nc.tif s3://covid-eo-data/OMNO2d_HRM-no2/OMI_trno2_0.10x0.10_202207_Col3_V4.nc.tif 
copy: s3://covid-eo-data/OMNO2d_HRM-no2-monthly-or-diff/OMI_trno2_0.10x0.10_202207_Col3_V4.nc.tif to s3://covid-eo-data/OMNO2d_HRM-no2/OMI_trno2_0.10x0.10_202207_Col3_V4.nc.tif
```

The legacy endpoint and payload in question
```
curl -X 'POST' \
  'https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/timelapse' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{"datasetId":"no2","dateRange":["201501","202209"],"geojson":{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[102.480912,29.152161],[102.480912,31.428663],[105.116931,31.428663],[105.116931,29.152161],[102.480912,29.152161]]]}}}'
```

For the EOX legacy timelapse endpoint bug: I noticed that:
- the two working dates for the time lapse endpoint correspond to the two differently named files above
- all the other no2 monthly files besides those two have a last modified date of 2022-06-24
- the no2-dff timelapse endpoint works as expected, the files in the no2-monthly diff folder (OMNO2d_HRMDifference) do not have a June 24 modified date


Now I am thinking that maybe the files in OMNO2d_HRM were re-named on June 24 to add monthly to the filename and differentiate from the monthly diff files stored under the OMNO2d_HRMDifference path. If the legacy covid-api has configuration for a different filename/path pattern it could be the cause of the broken timelapse endpoint.

**Comment by anayeaye** [comment]
Confirmed that renaming the files breaks the legacy API by copying an OMNO2d_HRM (no2-monthly) file to the old naming pattern and re-running the timelapse endpoint--now the date of the file copied to the old naming pattern is included in the timelapse result. 
```
% aws s3 cp s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_monthly_0.10x0.10_202205_Col3_V4.nc.tif s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_0.10x0.10_202205_Col3_V4.nc.tif 
copy: s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_monthly_0.10x0.10_202205_Col3_V4.nc.tif to s3://covid-eo-data/OMNO2d_HRM/OMI_trno2_0.10x0.10_202205_Col3_V4.nc.tif
```

I also logged in the the veda-data-store-staging bucket (serving the staging-stac APIs) and found that a full set of the original filenames and the renamed files are included in the no2-monthly diff path. This is likely related to the uniqueness requirement on STAC item ids in our pgstac backend--both NO2 and NO2Diff files use the same tif naming strategy.

The fix:
- [ ] The tif filenames in the `covid-eo-data/OMNO2d_HRM/` bucket should be reverted to the old pattern that is used by the covid-api to un-break the legacy (pre-veda)`/v1/timelapse` endpoint

These next actions need to be coordinated because we need the stac-api item record assets to match the data assets in S3. Check to see if we have duplicate items with the same id in both the no2-monthly and no2-montly diff collection because of the duplicated filenames. PgSTAC probably prevents this but it is possible that the item records could be inaccurately updated, i.e. if an no2-monthly-diff item with the same id as a no2-monthly item is ingested second, the original item properties could be impacted.
- [ ] A unique item naming strategy needs to be adopted to accommodate items from different collections that refer to assets with the same filename. As in, the current convention of using the default asset's filename as the item id would result in duplicates for these two tiffs from different collections
   - `s3://veda-data-store-staging/no2-monthly/OMI_trno2_0.10x0.10_201602_Col3_V4.nc.tif`
   - `s3://veda-data-store-staging/no2-monthly-diff/OMI_trno2_0.10x0.10_201602_Col3_V4.nc.tif`  
- [ ] The VEDA no2-monthly STAC collection needs to be re-created, probably the no2-monthly-diff collection as well
- [ ] The veda-data-store-staging/no2-monthly bucket needs to be de-duplicated

**Comment by anayeaye** [comment]
Revised list of steps to resolve:

- [ ] Confirm that renamed s3 assets in no2-monthly buckets are exactly the same as the originals in both covid-eo-data and veda-data-store-staging (file size comparison, count, spot comparison of a couple downloads in QGIS). This means that after updating our indexes we can remove the duplicate renamed files.
- [ ] Copy renamed s3 assets in covid-eo-data to original filename. Covid-api timelapse endpoint is fixed, duplicate S3 objects with `_monthly_` in filename are still present.
- [ ] Fix prefix for no2-monthly in veda-data-pipelines step function inputs (previously the prefix did not have a final / and caught both no2-monthly and no2-monthly-diff
- [ ] Re-ingest no2-monthly collection to pick up the s3 objects with the original filename. Now we can remove the items created for the duplicated s3 objects. Confirm that we created items for all of the s3 objects with the original filename 
```
-- the good items
SELECT id, collection, items."content"->'assets'->'cog_default'->>'href' 
FROM items 
WHERE collection = 'no2-monthly' AND 
	id LIKE 'OMI_trno2_0.10x0.%';
```
- [ ] In pgstac, select all items with renamed assets (those with `_monthly_` in id) and remove. 
```
-- the items added copying renamed objects to veda data store where original items were already stored
SELECT id, collection, items."content"->'assets'->'cog_default'->>'href' 
FROM items 
WHERE collection = 'no2-monthly' AND 
	id LIKE '%_monthly_%';
```
- [ ] In pgstac, select all items with assets in the no2-monthly-diff/ prefix and remove  
```
-- the items added with an overly permissive ingest prefix
SELECT id, collection, items."content"->'assets'->'cog_default'->>'href' 
FROM items 
WHERE collection = 'no2-monthly' AND
	items."content"->'assets'->'cog_default'->>'href' LIKE 's3://veda-data-store-staging/no2-monthly-diff/%';
```
- [ ] Now the index is correct, the s3 buckets should be cleaned up next--remove all duplicated objects by matching the renamed object pattern `OMI_trno2_monthly`. Remove duplicates in covid-eo-data and veda-data-pipelines-staging
- [ ] Now the index and s3 data stores are correct, but there are some new s3 objects in covid-eo-data. Open a ticket to identify who is adding these new monthly COGs and plan to update the no2 collections when new data are added to a bucket.

**Comment by anayeaye** [comment]
Update temporal extent of collection and default summaries after removing `no2-monthly-diff` assets from `no2-monthly` collection. The `no2-monthly-diff` collection begins in 2015, `no2-monthly` begins in 2016.

```
SELECT dashboard.update_collection_default_summaries('no2-monthly');

UPDATE collections SET
    content = content ||
    jsonb_build_object(
        'extent', jsonb_build_object(
            'spatial', jsonb_build_object(
                'bbox', collection_bbox(collections.id)
            ),
            'temporal', jsonb_build_object(
                'interval', collection_temporal_extent(collections.id)
            )
        )
    )
WHERE collections.id = 'no2-monthly';
```

**Comment by anayeaye** [comment]
Also alerted EOX about the updated extents
>Following up on this no2-monthly collection contains no2-monthly-diff assets problem in the staging-stac API:
We have identified and removed duplicated data (same dataset but different id containing _monthly_)
We have identified and removed the items with no2-monthly-diff assets (these were accidentally ingested with an overly permissive regex).
>
>The records in https://staging-stac.delta-backend.com/collections/no2-monthly have been verified and agree with the s3 assets in the veda-data-store.
>
>NOTE Removing the incorrect no2-monthly-diff assets from the no2-monthly collection changed the collection’s temporal extent. The no2-monthly-diff collection begins 2014-12-31, while the no2-monthly collection begins 2015-12-31.
The temporal extent and summaries have been updated for both collections. The previous extents were manually added, the updated extent was based on the exact start and end datetimes of the item records. I hope this change will not impact the dashboard.

**Comment by Catalina-Moller** [comment]
The no2-monthly and no2-monthly-diff overviews and exploration maps for the Air Quality and Covid-19 thematic areas have not been affected by the change. 

cc: @anayeaye

**Comment by gadomski** [comment]
Closing as done on the board.
