### ISSUE TITLE
Update deployment to use new `veda-auth` credentials

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data-pipelines#194]
# Description

Currently, two deployments of `veda-data-pipelines` exist:
1. veda-data-pipelines-dev
2. veda-data-pipelines-staging

Both of these use the `veda-auth` creds from `veda-auth-alukach` stack, which is an experimental stack.

After https://github.com/NASA-IMPACT/veda-auth/issues/5 is done and deployed and cognito secrets created in the secrets manager, we need to update the current deployments (dev and staging) to use the corresponding creds.

Related env var:
`COGNITO_APP_SECRET=`

**Comment by j08lue** [comment]
This might get superseded by the redesign of the workflows API testing credentials (rather than just using the role?) @anayeaye and @alukach know more

**Comment by gadomski** [comment]
Okay, this was moved to done so I'm closing as complete. Please re-open if that's incorrect.
