### ISSUE TITLE
Fix bounding in EPA COG assets [edit: issue renamed]

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data-pipelines#196]
# What
EPA assets cannot be zoomed > 0 in the dashboard. The fix is to recreate the COG assets with appropriate overviews.
<img width="300" alt="blurry-epa" src="https://user-images.githubusercontent.com/3386265/191807750-70cd21f1-8d44-42c2-bb52-5f27305c3a01.png">

**EPA COG info snippet**
```
rio cogeo info /vsis3/veda-data-store-staging/EIS/cog/EPA-inventory-2012/monthly/EPA-monthly-emissions_1B2b_Natural_Gas_Production_201208.tif

<SNIP>
Image Structure
    COMPRESSION: LZW
    INTERLEAVE: BAND
    LAYOUT: COG

IFD
    Id      Size           BlockSize     Decimation           
    0       700x350        512x512       0
    1       350x175        512x512       2
```

**LIS TWS COG info snippet for comparison w/overviews**
```
% rio cogeo info /vsis3/veda-data-store-staging/EIS/COG/LIS_TWS_ANOMALY/Anomaly_TWS_20020923.cog.tif 
<SNIP>

Image Metadata
    AREA_OR_POINT: Area
    OVR_RESAMPLING_ALG: NEAREST

Image Structure
    COMPRESSION: DEFLATE
    INTERLEAVE: BAND
    LAYOUT: COG

IFD
    Id      Size           BlockSize     Decimation           
    0       3600x1500      512x512       0
    1       1800x750       128x128       2
    2       900x375        128x128       4
```

# AC
- [ ] reprocessed data ingested into STAC 
- [ ] delta-config updated _if needed_ (i.e. if reprocessed data are ingested to new collections)
- [ ] EPA assets do not appear blurry at zoom > 0 in dashboard

**Comment by xhagrg** [comment]
@anayeaye if we reprocess the images and upload with the same filename to the bucket, do we even need to re-inges into STAC? Wondering if we even need to remove and update stac.

**Comment by anayeaye** [comment]
@xhagrg True, if we're confident about the new COGs replacing them in place would work without updating the STAC records. If it is an easy/safe operation we wouldn't need to update STAC or delta-config. Maybe add some sort of thorough dashboard QA AC step instead?

**Comment by xhagrg** [comment]
Yes, when i get the reprocessing done, will send it in the veda-dashboard channel and ask for review/tests in the dashboard?

**Comment by xhagrg** [comment]
<img width="851" alt="image (6)" src="https://user-images.githubusercontent.com/4485278/191850073-de80e935-6be8-4bc7-8004-bf518f521497.png">
the cogs look okay in qgis.

**Comment by xhagrg** [comment]
@anayeaye updated the overviews and uploaded, still the same behavior. 

<img width="827" alt="image" src="https://user-images.githubusercontent.com/4485278/191856017-1805e246-f8aa-44fe-b451-6f96f426db22.png">

**Comment by xhagrg** [comment]
it might be because of the min max zoom levels

**Comment by vincentsarago** [comment]
```
$ rio cogeo info EPA-daily-emissions_5_Forest_Fires_20120101.tif
...
Geo
    Crs:              EPSG:4326
    Origin:           (-129.99999694660497, 19.999999240339655)
    Resolution:       (0.09999999672558174, 0.0999999934417812)
    BoundingBox:      (-129.99999694660497, 54.99999694496308, -59.999999238697754, 19.999999240339655)
    MinZoom:          3
    MaxZoom:          4
...
```

>     BoundingBox:      (-129.99999694660497, 54.99999694496308, -59.999999238697754, 19.999999240339655)

BoundingBox is really weird because it should be `-129.99999694660497, 19.999999240339655, -59.999999238697754, 54.99999694496308,`


This issue then is that rio-tiler will always return `TileOutsideBounds` (en thus empty array) for this file because the geographic bounds is wrong!

**Comment by anayeaye** [comment]
Thanks @vincentsarago! I _think_ this is the [original processing script](https://github.com/ashiklom/veda-data-processing/blob/main/EPA-CH4-inventory/make-cog.py). I think we now have access to the raw data, so it sounds like we just need to try revisiting the nc to COG processing code check our bounds outputs until we get them right.

**Comment by xhagrg** [comment]
Will reprocess it and see if that works.

**Comment by xhagrg** [comment]
All of the EPA data is re-processed and currently loading fine.

Steps taken:
1. Update bounds to be in proper format.
2. Add CRS (when missing)
3. 25x the tiff file (using nearest neighbor) to get "higher" resolution.

**Comment by anayeaye** [comment]
This issue is ready for QA: All of the COG assets for the EPA-* datasets in the EIS thematic area of the dashboard were reprocessed to solve a problem in which users could not zoom in on the map (the data became blurry at all zooms greater than 0). We need to make sure that all datasets are still viewable in the map and that users can zoom in without seeing a blurry map. 
cc: @gmarichalgxc @Catalina-Moller @mmaniceraGXC

**Comment by xhagrg** [comment]
https://www.earthdata.nasa.gov/dashboard/eis/datasets/epa-other/explore?datetime=2012-01-01T00%3A00%3A00.000Z&layer=epa-daily-emissions_5_forest_fires&position=-92.3416%7C32.5267%7C4.22 

This should now be fixed.

**Comment by j08lue** [comment]
They are not blurry anymore, but should the data really look like this - blobs with some kind of interpolation towards the center?

![image](https://user-images.githubusercontent.com/3404817/200957332-de5de91f-ca57-4d3c-a934-9cb081710c43.png)

https://www.earthdata.nasa.gov/dashboard/eis/datasets/epa-other/explore?datetime=2012-01-01T00%3A00%3A00.000Z&layer=epa-daily-emissions_5_forest_fires&position=-96.0397%7C36.1956%7C8.93

Do we know who the data provider was, then I can double-check with them?

**Comment by Catalina-Moller** [comment]
The EPA Datasets are rendering as expected. 
But we have found one possible issue that has a low priority, this is: NASA-IMPACT/veda-data#68
