### ISSUE TITLE
Publish EIS Annual Fire-Hydro COGs

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data-pipelines#206]
# Background notes
There are 5 annual Fire-Hydro COGs currently available in `veda-data-store-staging`. I did a quick spotcheck and the COGs appear valid and ready to ingest. We need to create a STAC collection, ingest these 5 COGs, and configure a dataset in delta-config.

**Data prefix:** `EIS/COG/Fire-Hydro`
**Example key:** `3://veda-data-store-staging/EIS/COG/Fire-Hydro/mtbs_CONUS_2016.cog.tif`
[cog/viewer preview](https://staging-raster.delta-backend.com/cog/viewer?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/mtbs_CONUS_2016.cog.tif)

# Research + prepare processing for the dataset: Identify the dataset and what the processing needs are

1. Identify dataset and where it will be accessed from (HTTP from DAAC vs S3, for example). Check it's a good source with science team. Ask about specific variables and required spatial and temporal extent. Note many datasets will require back processing (e.g. generating cloud-optimized data for historical data).

    [Future: 2. If the dataset is ongoing (i.e. new files are continuously added and should be included in the dashboard), design and construct the scheduling + forward-processing workflow.]

2. If necessary, create COG or any other conversion / processing code and verify the COG output with a data product expert (for example, someone at the DAAC which hosts the native format) by sharing in a visual interface.

3. Identify the point of contact and ensure someone is providing them updates!

# Design the metadata and publish to the Dev API

1. If not already familiar with these conventions for generating STAC collection and item metadata:
       - Collections: https://github.com/NASA-IMPACT/delta-backend/issues/29 and STAC version 1.0 specification for collections
       - Items: https://github.com/NASA-IMPACT/delta-backend/issues/28 and STAC version 1.0 specification for items
       - NOTE: The delta-backend instructions are specific to datasets for the climate dashboard, however not all datasets are going to be a part of the visual layers for the dashboard so you can ignore the instructions that are specific to "dashboard" extension, "item_assets" in the collection and "cog_default" asset type in the item.

      A collection will need the following fields, some of which may be self-evident through the filename or an about page for the product, however there are many cases in which we may need to reach out to product owners to define the right values for these fields:
      
      - temporal interval
      - license
      - id
      - title
      - description
      - whether it is periodic or not on the dashboard
      - the dashboard time density
  
4. Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md

## Publish to the Staging API

Once the PR is approved, we can merge and publish those datasets to the Staging API

---

## AC
- [ ] STAC collection and item records published to staging-stac.delta-backend.com
- [ ] PR submitted to delta-config to add this collection to the EIS thematic area as a new dataset (or delta-config issue generated and help requested)

**Comment by anayeaye** [comment]
cc @aboydnw

**Comment by anayeaye** [comment]
Here are some collection level details from Shahryar's email when we pick up this ticket:
> temporal interval – 5 rasters at annual timescale – 2016 - 2020
    license – keep the same as last time, I think we used MIT
    id – mtbs-burn-severity
    title – MTBS Burn Severity
    description – Burn severities and extents of fires from Monitoring Trends in Burn Severity (MTBS) program during the years 2016-2020 over Western US
    whether it is periodic or not on the dashboard – static 5 rasters
    the dashboard time density – do you mean timescale of dataset, that should be 1 year

Additional notes from me:
**temporal interval:** this will be the RFC3339 interval between 2016-01-01 to 2020-12-31 (and it can be updated in the database after ingesting items)
**dashboard:periodic: true** this property is used by the dashboard UI and the dataset summarizer to determine if the data are delivered at equal intervals with a time step equal to the time density. If not periodic the dashboard summary will need to include a list of distinct datetime strings for the dashboard time picker.
**dashboard:time_density:** year

**Comment by anayeaye** [comment]
Sorry I didn't just drop a list when I first opened this issue. 

```
% aws s3 ls veda-data-store-staging/EIS/COG/Fire-Hydro/
2022-10-11 09:26:50   36115833 mtbs_CONUS_2016.cog.tif
2022-10-11 09:26:49   41115008 mtbs_CONUS_2017.cog.tif
2022-10-11 09:26:50   39492616 mtbs_CONUS_2018.cog.tif
2022-10-11 09:26:50   31364081 mtbs_CONUS_2019.cog.tif
2022-10-11 09:26:50   41699694 mtbs_CONUS_2020.cog.tif
```

**Comment by ividito** [comment]
delta-config PR - https://github.com/NASA-IMPACT/delta-config/pull/127

**Comment by Catalina-Moller** [comment]
@anayeaye @ividito 
I was testing the Dataset and I noticed that over the northern US the layer is rendered less than in the southern US. 
For example in 2020 you can see that above a line the layer is rendered less and below it is rendered more. 
Url: https://deploy-preview-127--visex.netlify.app/eis/datasets/mtbs-burn-severity/explore?datetime=2020-01-01T00%3A00%3A00.000Z&position=-119.6425%7C47.971%7C9.14

Evidence: [Video ](https://www.screencast.com/t/CZOe5A5A5n)

It is also suggested to add an indicator point that the layer only covers US. 
Since when the user enters to the exploration view he sees first the map of the whole world and as the layer covers small portions of US he can think that there is no layer in the Dataset.

**Comment by anayeaye** [comment]
@Catalina-Moller this is strange, I can see the same behavior at the URL above but I don't see it in the cog/viewer so I wonder if the mosaic request used by the dashboard is having a harder time with the search and/or file metadata. I see 'no assets found' error where I *think* there should be tiles. @vincentsarago do you think this could be another case where the COG metadata is working against us somehow?

**sample accessible file in UAH:** s3://covid-eo-data/20221107-burn-severity-sample/mtbs_CONUS_2020.cog.tif
**mosaic 404:** https://staging-raster.delta-backend.com/mosaic/tiles/d21acfffdbc85a489dc84728cd0a823e/WebMercatorQuad/10/173/354@1x?assets=cog_default&colormap_name=inferno_r&rescale=0,6
**mosaic info:** https://staging-raster.delta-backend.com/mosaic/d21acfffdbc85a489dc84728cd0a823e/info
**viewer:** https://staging-raster.delta-backend.com/cog/viewer?url=s3://covid-eo-data/20221107-burn-severity-sample/mtbs_CONUS_2020.cog.tif

**Comment by j08lue** [comment]
We decided to mark this ticket as complete, since the issue is only a geographic edge case and much of the data renders fine. We will track the issue separately and hopefully find a solution a bit later.

Thanks for catching this and the great documentation, @Catalina-Moller!
