### ISSUE TITLE
When zooming in the Dataset "GEOGLAM Crop Conditions" the background of the layer is shown in black. 

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-data-pipelines#207]
**Description:** 
On the dates Jul 2020, Aug 2020, Sep 2020 and Oct 2020 when the user zooming in the background of the layer is shown in black color and it is not allowed to see the map below the layer. 
On the other dates the layer shows colored dots without the black background. 

**Evidence:** [Video](https://www.screencast.com/t/tCqq4Vxe)

![imagen_2022-10-24_103927079](https://user-images.githubusercontent.com/111894012/197539393-8de9ac6f-f9fc-484e-8f61-94fc0aaa95a4.png)

**Url:** https://www.earthdata.nasa.gov/dashboard/agriculture/datasets/geoglam/explore?datetime=2020-07-01T00%3A00%3A00.000Z&position=24.0775%7C40.5713%7C2.93

### **Acceptance Criteria:**
When the user zooms into the Dataset "GEOGLAM Crop Conditions" at any date the background of the layer is transparent and the user can see the map below the layer.

**Comment by vincentsarago** [comment]
I think it might be a nodata issue on the overviews! can you share the files?

**Comment by smohiudd** [comment]
Thanks @vincentsarago for your help with this.

@j08lue, looks like the data provider has used differnt configurations for differneet COGs in this set. There are three types of files I've seen so far with the following ranges:

1..7 - `nodata` value and mask works in all zoom level  :white_check_mark:
1..15 - issues with `nodata` values :heavy_multiplication_x:
1..99 - `nodata` value and mask works in all zoom level :white_check_mark:

In all three cases the `nodata` value in the COG is set to 99.

Can we ask them to reprocess 07, 08, 09, 10 from 2022 to be from the 1 to 99 range?

**Comment by j08lue** [comment]
Hmm, there do not seem to be any issues with rendering the very same COGs in the COVID-19 Dashboard, including for example July 2022: https://www.earthdata.nasa.gov/covid19/explore/global?map=5.3967%2C12.7544%2C4.44&layers=agriculture&date=2022-07-01&lState=no2%7C0%7C50%2Cagriculture%7C0%7C0

with calls like https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/5/15/12@1x?url=s3://covid-eo-data/agriculture-cropmonitor/CropMonitor_202207.tif&resampling_method=nearest&bidx=1&color_map=custom_cropmonitor

It might help to know how exactly that color map `custom_cropmonitor` is defined. Do you know where to find it, @vincentsarago or perhaps @leothomas https://github.com/NASA-IMPACT/covid-dashboard? Perhaps in the config for the TiTiler instance https://github.com/NASA-IMPACT/covid-api/?

Data ranges 1-7 make sense - there are 7 classes in the data (plus nodata value)
![image](https://user-images.githubusercontent.com/3404817/208084546-55fe4bfc-8974-4ebe-bb07-60d956f5b1ae.png)

If the range is 1-99, I guess that means 99 is not really flagged as nodata?

1-15 smells like some 99 got mixed in during reprojection or so. 🤷 

Can you please list the names of the files that are affected, @smohiudd? Then I'll ask the provider to fix them.

**Comment by smohiudd** [comment]
@j08lue, Jul 2020, Aug 2020, Sep 2020 and Oct 2020 were the issues and you can see the same in the covid dashboard: https://www.earthdata.nasa.gov/covid19/explore/global?map=4.8504%2C36.3921%2C3.46&layers=agriculture&date=2020-07-01&lState=no2%7C0%7C50%2Cagriculture%7C0%7C0

As far as I can tell, the files I listed above are the only ones that have the range 1..15

**Comment by j08lue** [comment]
I think we should just fix the files for them, please.

Looks like the pixel values are ok and it is just the overviews that are broken. So we just need to cloud-optimize the files again to get working files: `rio cogeo create --overview-resampling mode`.

Ideally, we should also do that for the earlier files that seem to render fine. When I calculate stats on the November 2022 file `rio info --stats`, it also shows a range up to 99 and cloud-optimization fixes that.

```bash
$ rio cogeo create --overview-resampling mode CropMonitor_2022_10_28.tif CropMonitor_2022_10_28-cog.tif          
Reading input: /Users/jonassolvsteen/Data/crop-monitor-data-issue/CropMonitor_2022_10_28.tif
  [####################################]  100%          
Adding overviews...
Updating dataset tags...
Writing output to: CropMonitor_2022_10_28-cog.tif
$ rio info CropMonitor_2022_10_28.tif --stats                                                          
1.0 99.0 95.513024422773 17.934460985463
$ rio info CropMonitor_2022_10_28-cog.tif --stats
1.0 7.0 3.2880207882831156 1.2677713455772666
```

I will also ask the data provider to look into changing their process. But we should consider making this part of our pipeline. Way too many issues with this...

**Comment by smohiudd** [comment]
July-Oct 2020 COGs are fixed now and uploaded. They're showing up correctly in the dashboard. @j08lue recreating the overviews didn't work for me, what I did was assign the `nodata` values in those COGs to 15. 

The COGs that have a 99 `nodata` value are all ok as mentioned [here](https://github.com/NASA-IMPACT/veda-data-pipelines/issues/207#issuecomment-1353751416) so if the data provider continues to do this it should be ok.

**Comment by j08lue** [comment]
Oh, the bad ones were from 2020, not 2022. Sorry, my bad! Great you were able to fix them.

I still think there is something weird going on with even the latest files, because the stats computation includes the fill value... But if it works... 🤷

**Comment by j08lue** [comment]
This one was completed.
