### ISSUE TITLE
On two dates no layer is shown in the Dataset "GEOGLAM Crop Conditions"

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-data-pipelines#208]
**Description:** 
In December 2020 and December 2021 the user only sees the map as no layers are shown in the Dataset "GEOGLAM Crop Conditions". 

**Evidence:** 
Dec 2020:
Url:https://www.earthdata.nasa.gov/dashboard/agriculture/datasets/geoglam/explore?datetime=2020-12-01T00%3A00%3A00.000Z&position=0%7C21.7558%7C1.12

![image](https://user-images.githubusercontent.com/111894012/197604224-49015b07-aa1a-4dbd-b929-b6db71e01d48.png)

Dec 2021:
Url:https://www.earthdata.nasa.gov/dashboard/agriculture/datasets/geoglam/explore?datetime=2021-12-01T00%3A00%3A00.000Z&position=0%7C21.7558%7C1.12 
 
![image](https://user-images.githubusercontent.com/111894012/197604315-37fdaf25-c461-4d4e-93df-52b3226dc548.png)

**Acceptance Criteria:**
The user should see a layer covering the map of the "GEOGLAM Crop Conditions" Dataset on each available date.

**Comment by moradology** [comment]
Just verified that this record isn't ingested. We should see 3 items here rather than just Nov and Jan: https://staging-stac.delta-backend.com/search?collections=geoglam&limit=100&datetime=2020-11-01T00:00:00.000Z/2021-01-01T00:00:00.000Z

**Comment by j08lue** [comment]
I asked the data provider about the December data and they reported that they do not produce data for December.

> The GEOGLAM Crop Monitor crop condition maps are a consensus product based upon the inputs of dozens of national and regional specialists. As such, we have found that too many of our partners are out of the office during the end of December in order to produce a full product. So December is currently the one month of the year that we do not produce data.

I will close this ticket but will open a ticket with the UI development to consider skipping these time steps for the user, so there is no confusion.
