### ISSUE TITLE
Change "Carbon Dioxide" dataset to non-periodic

### ISSUE THREAD

**Issue by Catalina-Moller** [NASA-IMPACT/veda-data-pipelines#209]
Same as #221 

The dataset is configured as periodic, which means that the frontend shows date options for all periods within range. In fact, it is not periodic - some dates are missing. Changing the configuration should make the frontend only show the available dates.

## Issue description from QA

**Description:**
In the Dataset "Carbon Dioxide" no layer is shown on the map between December 17 and December 31 of the years 2015, 2016, 2017, 2018, 2019, 2020 and 2021 in the layer "Mean CO2" and "Difference CO2".

**Evidence:** 
**Mean CO2:**
Url: https://www.earthdata.nasa.gov/dashboard/airquality/datasets/co2/exploreposition=-2.5266%7C21.2853%7C1.65&datetime=2015-12-17T00%3A00%3A00.000Z 
![image](https://user-images.githubusercontent.com/111894012/197604743-0e885dae-7d69-45cf-9411-77fa5ae9eb95.png)

**Difference CO2:**
Url: https://www.earthdata.nasa.gov/dashboard/airquality/datasets/co2/exploreposition=-2.5266%7C21.2853%7C1.65&datetime=2015-12-17T00%3A00%3A00.000Z&layer=co2-diff 
![image](https://user-images.githubusercontent.com/111894012/197604815-2dfb63e6-a0eb-4c86-a647-9145778282cb.png)

### **Acceptance Criteria:**
The user should see a layer covering the map of the "Carbon Dioxide" Dataset on each available date in the layer "Mean CO2" and "Difference CO2".

**Comment by j08lue** [comment]
Who is the provider, so we can ask whether the missing time steps should be missing?

If it turns out they simply do not exist, we should change the dataset to non-periodic, like https://github.com/NASA-IMPACT/veda-data-pipelines/issues/221, as @Catalina-Moller pointed out.

**Comment by connectwithprakash** [comment]
The reason indeed is because of the unavailability of the data for those dates in any of the staging, dev, or UAH bucket.
