### ISSUE TITLE
Add ECCO ocean state estimate

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#217]
- [x] Identify data location `s3://veda-data-store-staging/EIS/COG/SSH_2017_minus_1992.cog.tif`
- [x] Number of items: 1
- [x] Identify the point of contact and ensure someone is providing them updates: Denis, @j08lue to follow up 
- [x] Verify data is valid COG
- [ ] Gather STAC collection metadata
   - temporal interval: 
   - license: 
   - id: 
   - title: `ECCO sea-surface height change from 1992 to 2017`
   - description: 
     Gridded global sea-surface height change from 1992 to 2017 from the Estimating the Circulation and Climate of the Ocean (ECCO) ocean state estimate. The dataset was calculated as the difference between the annual means over 2017 and 1992, from the 0.5 degree, gridded monthly mean data product available on PO.DAAC (https://podaac.jpl.nasa.gov/dataset/ECCO_L4_SSH_05DEG_MONTHLY_V4R4).
   - whether it is periodic or not on the dashboard: `periodic: false`
   - the dashboard time density: 

- [ ] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md
- [ ] Once the PR is approved, we can merge and publish those datasets to the Staging API

## Resources about metadata

- Collections: https://github.com/NASA-IMPACT/delta-backend/issues/29 and STAC version 1.0 specification for collections
- Items: https://github.com/NASA-IMPACT/delta-backend/issues/28 and STAC version 1.0 specification for items
- NOTE: The delta-backend instructions are specific to datasets for the climate dashboard, however not all datasets are going to be a part of the visual layers for the dashboard so you can ignore the instructions that are specific to "dashboard" extension, "item_assets" in the collection and "cog_default" asset type in the item.

**Comment by anayeaye** [comment]
### STAC metadata notes
- Number of items: 1 
- `dashboard:is_periodic` = `false`, the dashboard will not need to construct a series of periodic dates for the time picker and can instead use the temporal range of collection
- `dashboard:time_density` = `null`, there are not daily, monthly, etc items

### Asset notes
- The COG appears to be valid COG but has no data pixels. We need this data to be recreated.
- We can access the COG from our titler COG preview: https://staging-raster.delta-backend.com/cog/viewer?url=s3://veda-data-store-staging/EIS/COG/SSH_2017_minus_1992.cog.tif
- **But:** the /cog/statistics endpoint returns an error, because there are no image layers in the COG (I also downloaded to be sure) https://staging-raster.delta-backend.com/cog/statistics?url=s3%3A%2F%2Fveda-data-store-staging%2FEIS%2FCOG%2FSSH_2017_minus_1992.cog.tif&unscale=false&resampling=nearest&categorical=false&p=2&p=5&p=95&p=98&histogram_bins=8
`detail	"cannot do a non-empty take from an empty axes."`

**Comment by dfelikson** [comment]
Sorry about this! I'm not sure what happened but I provided a bad version of the tif. I've replaced the COG with a version that does contain data: s3://veda-data-store-staging/EIS/COG/SSH_2017_minus_1992.cog.tif

**Comment by j08lue** [comment]
Great, looks good now:

![image](https://user-images.githubusercontent.com/3404817/199452473-51c86521-549b-48db-9208-632c408575c6.png)

**Comment by anayeaye** [comment]
companion delta-config issue https://github.com/NASA-IMPACT/delta-config/issues/128

**Comment by j08lue** [comment]
Wait a sec. There might be an issue with this COG (or some `mosaic.json`?), @dfelikson. When I preview it in the COG viewer ([`/cog/viewer`](https://staging-raster.delta-backend.com/cog/viewer?url=s3://veda-data-store-staging/EIS/COG/SSH_2017_minus_1992.cog.tif)), it does not zoom:

![image](https://user-images.githubusercontent.com/3404817/201315318-08f41f8c-023b-4b5a-b726-3dea2a9023ca.png)

And I can see from the settings for this dataset ([`/cog/validate`](https://staging-raster.delta-backend.com/cog/validate?url=s3://veda-data-store-staging/EIS/COG/SSH_2017_minus_1992.cog.tif)) that it uses

```json
{"MinZoom":0,"MaxZoom":1}
```

What code are you using to create the COGs, @dfelikson?

@vincentsarago, could I ask you to help explain where `MinZoom` and `MaxZoom` come from? Is that setting stored in the COG header or does it come from some `mosaic.json`? I can see this is a delicate piece of information... https://github.com/developmentseed/titiler/issues/291

**Comment by vincentsarago** [comment]
@j08lue in `/cog/validate` the zoom informations are derived from the size of the file (resolution) once reprojected to the WebMercator TMS. maxzoom=1 could mean that either your file is small or there is an issue with it's bounds (or there is a bug in rio-tiler 😓) 

can you share the result of `/cog/info` for the file?

For the mosaic, the min/max zoom are usually equal to the zoom `available` for the COGs

**Comment by j08lue** [comment]
https://staging-raster.delta-backend.com/cog/viewer?url=s3://veda-data-store-staging/EIS/COG/SSH_2017_minus_1992.cog.tif

https://staging-raster.delta-backend.com/cog/info?url=s3://veda-data-store-staging/EIS/COG/SSH_2017_minus_1992.cog.tif
```json
{"bounds":[-180.0,-90.0,180.0,90.0],"minzoom":0,"maxzoom":1,"band_metadata":[["1",{}]],"band_descriptions":[["1",""]],"dtype":"float32","nodata_type":"Nodata","colorinterp":["gray"],"width":720,"nodata_value":-9999.0,"height":360,"overviews":[2],"driver":"GTiff","count":1}
```

**Comment by vincentsarago** [comment]
> "height":360

It's small dataset covering a huge area so the resolution is big and this the max Zoom is low

**Comment by j08lue** [comment]
Oh, my bad. Sorry for the fuss! I have rarely worked with data that coarse lately, therefore I did not even consider looking at the native resolution... 🤦 

All as it should be, then.
