### ISSUE TITLE
Add new VEDA dataset: Global TWS non-stationarity index

### ISSUE THREAD

**Issue by dfelikson** [NASA-IMPACT/veda-data-pipelines#224]
- [x] Identify the point of contact and ensure someone is providing them updates: @dfelikson and @j08lue 
- [x] Identify data location `s3://veda-data-store-staging/EIS/Global_TWS_data/DATWS_nonstationarity_index_v2.cog.tif`
- [x] Number of items: 1
- [x] Verify data is valid COG
- [x] Gather STAC collection metadata
   - id: `lis-tws-nonstationarity-index`
   - title: `Global TWS non-stationarity index`
  - description: The global Terrestrial Water Storage (TWS) non-stationarity index integrates the trend, seasonal shifts, and variability change of TWS for the period of 2003 - 2020. TWS is derived by jointly assimilating the MODIS Leaf Area Index, the ESACCI surface soil moisture, and the GSFC GRACE mascon-based TWS anomalies into the Noah-MP land surface model within the NASA Land Information System (LIS) at 10 km spatial resolution forced by the combination of MERRA2 and IMERG meteorological fields. The smaller the non-stationarity index is, the more the water cycle is under a non-stationary process. Glaciers and Greenland are excluded from the analysis.
  - license: Creative Commons Zero ([CC0-1.0](https://spdx.org/licenses/CC0-1.0.html))
  - temporal interval: `2003 - 2020`
  - whether it is periodic on the dashboard (periodic = regular time series of layers without gaps): `false`
  - the dashboard time density: `none`

- [ ] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md
- [ ] Open PR for publishing those datasets to the Staging API:
- [ ] Notify QA / move ticket to QA state
- [ ] Once approved, merge and close.

## Resources about metadata

- Collections: https://github.com/NASA-IMPACT/delta-backend/issues/29 and STAC version 1.0 specification for collections
- Items: https://github.com/NASA-IMPACT/delta-backend/issues/28 and STAC version 1.0 specification for items
- NOTE: The delta-backend instructions are specific to datasets for the climate dashboard, however not all datasets are going to be a part of the visual layers for the dashboard so you can ignore the instructions that are specific to "dashboard" extension, "item_assets" in the collection and "cog_default" asset type in the item.

**Comment by anayeaye** [comment]
@dfelikson can these files be reprocessed/re-uploaded with the `.tif` extension instead of `.COG`? Gdalinfo is able to read the data but these files are not working seamlessly with our raster services. I think the problem is just the extension 🤞 .

https://staging-raster.delta-backend.com/cog/viewer?url=s3://veda-data-store-staging/EIS/COG/coastal-flooding-and-slr/MODIS_LC_2001_BD.COG

https://staging-raster.delta-backend.com/cog/validate?url=s3://veda-data-store-staging/EIS/COG/coastal-flooding-and-slr/MODIS_LC_2001_BD.COG

**Comment by dfelikson** [comment]
The COG files were renamed to `*.cog.tif`.

**Comment by dfelikson** [comment]
I tried verifying the validity using `rio cogeo validate` but got a warning:

```
/srv/conda/envs/notebook/lib/python3.9/site-packages/rasterio/__init__.py:277: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix will be returned.
  dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
/home/jovyan/DATWS_nonstationarity_index.cog.tif is a valid cloud optimized GeoTIFF
```

@j08lue - is the missing geotransform going to be a problem? I'm guessing it will be but wanted to double check.

**Comment by dfelikson** [comment]
@j08lue - I uploaded an updated dataset to the same S3 location (`s3://veda-data-store-staging/EIS/Global_TWS_data/DATWS_nonstationarity_index.cog.tif`) with updated spatial coordinates. Please have a look and let me know if this works.

**Comment by j08lue** [comment]
You can test it yourself with a URL like this: https://staging-raster.delta-backend.com/cog/statistics?url=s3://veda-data-store-staging/EIS/Global_TWS_data/DATWS_nonstationarity_index.cog.tif - unfortunately still the same?

**Comment by dfelikson** [comment]
Ah ha! Thanks for the tip with that URL. I think it was an issue with AWS not letting me overwrite the previous version of the file. I uploaded a new file (`s3://veda-data-store-staging/EIS/Global_TWS_data/DATWS_nonstationarity_index_v2.cog.tif`) and it passed the URL test.

**Comment by j08lue** [comment]
@dfelikson Cool, thanks. For visual QA (always a good idea so you can spot resampling issues - e.g. when you chose bilinear interpolation for overviews on a categorical dataset), you can also use https://staging-raster.delta-backend.com/cog/viewer?url=s3://veda-data-store-staging/EIS/Global_TWS_data/DATWS_nonstationarity_index_v2.cog.tif

And it looks good:

![image](https://user-images.githubusercontent.com/3404817/201311054-750d3835-c691-4d92-b29c-68dc7d8544ed.png)

**Comment by j08lue** [comment]
We just need the rest of the metadata now, please, then we can ingest this.

**Comment by abarciauskas-bgse** [comment]
@dfelikson 👋🏽 I am going to help finish ingesting this dataset and just wanted to double check:

>I've added all necessary STAC metadata.

Do you just mean you added the STAC metadata content to this issue in the first comment or added it someplace else? I don't see this dataset in the STAC API (and was assuming that is what I could help with) but wanted to double check.

**Comment by dfelikson** [comment]
Hi @abarciauskas-bgse! Thanks for your help. Yes, I meant I just added it to the first comment. Let me know if I need to do something else or if you need more info.

**Comment by dfelikson** [comment]
I'm not 100% sure but I don't really think we have a preference. Can this be updated later?

**Comment by abarciauskas-bgse** [comment]
@dfelikson yes no problem - I have ingested the collection and item to our DEV API and database - https://dev-stac.delta-backend.com/collections/lis-tws-nonstationarity-index - do you want to take a look and let me know it looks ok?

(Btw, I need to find out why the summaries only shows the start date and if that's a problem)

**Comment by dfelikson** [comment]
@abarciauskas-bgse - looks good to me on first glance! Now that it's in the API and database, can I try adding it to the discovery?

**Comment by abarciauskas-bgse** [comment]
Shortly! I'm in meetings for a bit but will add it to the staging database in the next few hours

**Comment by dfelikson** [comment]
No worries at all! Thanks, @abarciauskas-bgse - still learning how this process works.

**Comment by abarciauskas-bgse** [comment]
@dfelikson ok this has been inserted into staging and you should be able to configure the discovery with it https://staging-stac.delta-backend.com/collections/lis-tws-nonstationarity-index

**Comment by dfelikson** [comment]
I need a little help, @abarciauskas-bgse. Here's how I configured it in the Discovery:

```
<Block type='full'>
  <Figure>
    <Map
      datasetId='lis-tws-nonstationarity-index'
      layerId='lis-tws-nonstationarity-index'
      dateTime='2003-01-01'
      zoom={1}
      center={[0,0]}
    />
    <Caption 
      attrAuthor='NASA' 
      attrUrl='https://nasa.gov/'
    />
  </Figure>
 </Block>
```

But I must have either the datasetID, layerID, or dateTime configured wrong because it's not showing up. I took a look through the metadata https://staging-stac.delta-backend.com/collections/lis-tws-nonstationarity-index and I see an id but I don't see different ids for the dataset vs layer. Is there another endpoint that will show me that?

**Comment by j08lue** [comment]
The dataset and layers need to be set up in `delta-config/datasets` first. We need a PR against `delta-config` for that, like https://github.com/NASA-IMPACT/delta-config/pull/143.

https://github.com/NASA-IMPACT/delta-config/blob/develop/docs/CONTENT.md#datasets
