### ISSUE TITLE
Add new VEDA dataset: Annual LAI maps for 2003 and 2021

### ISSUE THREAD

**Issue by dfelikson** [NASA-IMPACT/veda-data-pipelines#225]
- [x] Identify the point of contact and ensure someone is providing them updates: @dfelikson and @j08lue 
- [x] Identify data location:
   - `s3://veda-data-store-staging/EIS/COG/coastal-flooding-and-slr/MODIS_LAI_2003_BD.cog.tif`
   - `s3://veda-data-store-staging/EIS/COG/coastal-flooding-and-slr/MODIS_LAI_2020_BD.cog.tif`
- [x] Number of items: 2
- [x] Notes: This will be displayed with a slider so the user can contrast the two maps.
- [x] Verify that files are valid COGs (e.g. with `rio cogeo validate`): @dfelikson verified with `rio cogeo validate` 
- [x] Gather STAC collection metadata

  - id: `modis-annual-lai-2003-2020`
  - title: `Annual LAI maps for 2003 and 2020`
  - description: The annual median Leaf Area Index (LAI) maps of 2003 and 2020 were captured using combined Moderate Resolution Imaging Spectroradiometer (MODIS) Level 4 dataset (MCD15A3H Version 6.1, dataset link: https://modis.gsfc.nasa.gov/data/dataprod/mod15.php). The actual dataset represents one-sided green leaf area per unit ground area at 500 meters spatial resolution and provides information at every 4 days. Annual median of the LAI datasets were calculated for both the years of 2003 and 2020 to illustrate the difference in vegetation cover.
  - license: Creative Commons Zero ([CC0-1.0](https://spdx.org/licenses/CC0-1.0.html))
  - temporal interval:
     - `MODIS_LAI_2003_BD.cog.tif: {"start_datetime": "2003-01-01T00:00:00+00:00", "end_datetime": "2003-12-31T23:59:00+00:00"}`
     - `MODIS_LAI_2020_BD.cog.tif: {"start_datetime": "2020-01-01T00:00:00+00:00", "end_datetime": "2020-12-31T23:59:00+00:00"}`
  - whether it is periodic on the dashboard (periodic = regular time series of layers without gaps): `false`
  - the dashboard time density: `none`

- [x] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md
- [x] Open PR for publishing those datasets to the Staging API:
- [ ] Notify QA / move ticket to QA state
- [ ] Once approved, merge and close.

## Resources on metadata

If not already familiar with these conventions for generating STAC collection and item metadata:
       - Collections: https://github.com/NASA-IMPACT/delta-backend/issues/29 and STAC version 1.0 specification for collections
       - Items: https://github.com/NASA-IMPACT/delta-backend/issues/28 and STAC version 1.0 specification for items
       - NOTE: The delta-backend instructions are specific to datasets for the climate dashboard, however not all datasets are going to be a part of the visual layers for the dashboard so you can ignore the instructions that are specific to "dashboard" extension, "item_assets" in the collection and "cog_default" asset type in the item.

**Comment by dfelikson** [comment]
Files were renamed to `*.cog.tif`.

**Comment by j08lue** [comment]
Do we need reference dates for these annual aggregates? E.g. 1st of January of the respective year?

**Comment by dfelikson** [comment]
If you need to assign a specific date, I would use July 1 of each respective year to indicate that it's the average over the entire year. Not sure if it's possible but if there's a place to store the temporal bounds over which these were computed (Jan 1 - Dec 31), that would be great, too.

**Comment by j08lue** [comment]
> Not sure if it's possible but if there's a place to store the temporal bounds over which these were computed (Jan 1 - Dec 31), that would be great, too.

@anayeaye, can you answer this?

**Comment by anayeaye** [comment]
This sounds like one where we'd want to use start and end datetimes instead of a nominal single datetime property. The ingest pipelines will be able to handle this if the ranges are known and consistent.

So instead we'd want something like this in the stac item record for the 2003 COG:
`start_datetime`: `2003-01-01T00:00:00+00:00`
`end_datetime`: `2003-12-31T23:59:00+00:00`

I can't remember the preferred way to represent the end datetime (if not inclusive maybe end datetime is the first instant of 2004). Either way any stac search between January 1 and December 31 of 2003 ought to hit this item.

**Comment by j08lue** [comment]
Great. With this, we have all the required information, I think.

**Comment by dfelikson** [comment]
@j08lue I just invented one and added it. I think it's specific enough without being too long. See what you think. Is that the final piece to being able to ingest this dataset?

**Comment by ividito** [comment]
We're still working on getting this dataset ingested on our staging environment. It requires a [bugfix](https://github.com/NASA-IMPACT/veda-stac-ingestor/pull/20) which we're still testing. In the meantime, the collection is available on our [dev environment](https://radiantearth.github.io/stac-browser/#/external/dev-stac.delta-backend.com/collections/modis-annual-lai-2003-2020).

**Comment by ividito** [comment]
This dataset has been ingested and can be previewed here: http://localhost:9000/eis/datasets/modis-annual-lai-2003-2020/explore?position=91.4689%7C24.3586%7C7.6&datetime=2003-01-01T00%3A00%3A00.000Z

There seem to be a few holes in the dataset - @dfelikson can you confirm that the dataset appears as intended? 
![image](https://user-images.githubusercontent.com/19193384/202796365-5f4df5a5-4a46-49f3-9b5c-029511b8ff5a.png)

**Comment by ashiklom** [comment]
@ividito That looks good to me, thanks! Let me know when you have pushed that and I will add it to the coastal risk discovery (https://github.com/NASA-IMPACT/delta-config/pull/138).

**Comment by ividito** [comment]
@ashiklom Should be available on the staging environment now 👍

**Comment by ividito** [comment]
Copying some issues reported in https://github.com/NASA-IMPACT/delta-config/pull/138

> Made some progress on this. A few notes:
> 
>     * On closer inspection, LAI values are crazy. Usually, LAI is between 0 for bare ground and maybe like 3-4 for dense forest, and maybe 7 or 8 occurring in the densest tropical forests in the world. 63 is wildly unreasonable. Spatial patterns look reasonable, though. I wonder of there's an extra factor of 10 in here somewhere.
> 
>     * Is the second LAI map for 2021 or 2020? STAC metadata has 2020, but name and description say 2021. Should be a simple fix.
> 
>     * For some reason, I can independently visualize LAI for 2003 and 2020 (by setting the `dateTime`) in the discovery, but the comparison slider always fails to render the second layer (regardless of the direction of comparison). Other seemingly identically-configured comparisons work just fine.


The latter 2 issues should be straightforward fixes on our end, but the first issue seems to be an issue with the geotiffs themselves. Once new data has been uploaded, we can revisit this issue.

**Comment by Catalina-Moller** [comment]
Two different views of the layer are shown, one is missing a part of the layer and the other view (with a higher zoom) is not. 

This is the issue reported with its specific evidence: #244.

**Comment by gmarichalgxc** [comment]
Move this to Done, QA activities finished.
Related bug is created in the #244 .
