### ISSUE TITLE
Identify why date ranges are causing issues

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#234]
## Steps to reproduce:

1. Ingest records without single datetime but only `start_date` and `end_date`
2. Run pipeline
3. ...?

## Workaround for dataset ingestion:
- Use single datetime instead

## Acceptance criteria
- [x] Issue identified and new ticket raised in case it needs fixing

**Comment by moradology** [comment]
Here's the bit of code used by the stac building lambda which is relevant for interpreting datetime arguments: https://github.com/NASA-IMPACT/veda-data-pipelines/blob/main/lambdas/build-stac/utils/stac.py#L77-L107

**Comment by vlulla** [comment]
It appears that i made the mistake of setting `"datetime_range": "year"` when I tried to ingest these two landcover items. Instead, it appears that I ought to have used `"start_datetime": "2001-01-01T00:00:00Z", "end_datetime":"2001-12-31T23:59:59Z"` for each of the item entries listed in the `data/step_functions_input/bangladesh-landcover-2001-2020.json`! @moradology and I checked to ensure that setting `"start_datetime"` and `"end_datetie"` correctly inserts the stac items and does not break either the netlify preview or the stac item search.

**Comment by slesaad** [comment]
@vlulla it's not a mistake, that was supposed to work, but apparently doesn't. I've been looking at the code that @moradology linked above, and the discrepancy I found between setting the `start_datetime` and `end_datetime` ourselves and letting the code generate it for us via the `datetime_range` property is that the latter creates a datetime string without the `Z` at the end. I haven't tested the whole thing, but I suspect that might be the cause of our issue.

**Comment by j08lue** [comment]
Question answered for this round - still follow-up questions, perhaps, to surface elswhere.
