### ISSUE TITLE
Only above some latitude, data stays blurry at high zoom levels

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#235]
This is a spin-out issue from QA on MTBS (burn severity) data we ingested (#206).

The problem is reproducible and well documented here: https://github.com/NASA-IMPACT/veda-data-pipelines/issues/206#issuecomment-1306005960

## In short:
1. Zoom into MTBS data 
2. South of some arbitrary latitude, all looks fine
3. North of that, data does not get rendered at higher zoom levels but stays blurry.

## Acceptance criteria
- [x] Data is rendered at its maximum native resolution throughout the entire data domain

**Comment by j08lue** [comment]
Y-flipped rasters (with corresponding transforms) are such a classic cause of trouble... Do we compute those bounding boxes or did the users provide them?

We all know this, I guess - you have to be extra careful when creating bounding boxes from bounds (which are created from the affine transform). Rasterio has some code on this - it is basically just about an extra min/max instead of relying on the order of the bounds:

https://github.com/rasterio/rasterio/blob/6bb3e52e19826845701c335fb58c142d2d6baa53/rasterio/rio/bounds.py#L76

**Comment by j08lue** [comment]
Great you found the origin, @smohiudd, this was such a strange bug...

**Comment by smohiudd** [comment]
> Great you found the origin, @smohiudd, this was such a strange bug...

@vincentsarago was a big help with this

**Comment by j08lue** [comment]
Error still persists e.g. for MTBS burn severity:

![Image](https://user-images.githubusercontent.com/3404817/229050676-2242334d-c0df-4ea8-bc56-6fb03ce822ea.png)

https://www.earthdata.nasa.gov/dashboard/eis/datasets/mtbs-burn-severity/explore?datetime=2020-01-01T00%3A00%3A00.000Z&position=-119.769%7C48.0457%7C9.13

**Comment by smohiudd** [comment]
@j08lue the MTBS problem is a bit strange. It's an error with bounding box as mentioned above but the main source of the problem may be an incorrect projection. I'm still investigating this along with @sahmad3. Hoping we can resolve this soon...

**Comment by smohiudd** [comment]
Ok finally getting close to solving this stubborn bug. Thanks @anayeaye, @ividito, @vincentsarago for your help with this. 

This looks like a problem with the re-projection from the COG crs (for MTBS this is the [Albers projection](https://en.wikipedia.org/wiki/Albers_projection)) to WGS84 before storing the bbox in the db.

We can see this problem when looking at the bounding box for 2016 MTBS:

[COG bbox](https://staging-raster.delta-backend.com/cog/info?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/mtbs_CONUS_2016.cog.tif): [-126.49459612498832,24.0478678762251,-71.50752568733597,50.55916724898132]

[Pgstac bbox](https://dev-stac.delta-backend.com/collections/mtbs-burn-severity/items/mtbs_CONUS_2016.cog): [-126.49459612498832,24.0478678762251,-71.50752568733597,48.41970604505428]


Here is an image that shows the problem (source: @vincentsarago)
![Image](https://user-images.githubusercontent.com/34844565/229881933-631c2e89-fd26-404f-a564-1a68b96db689.png)

We've traced the problem to `build_stac` in `veda-data-pipelines` that uses `rio_stac` to create the stac item. This method uses:

```
src_geom = bbox_to_geom(src_dst.bounds)
geom = warp.transform_geom(src_dst.crs, "epsg:4326", src_geom)
```

The solution may be to use `warp.transform_bounds(src_dst.crs, "epsg:4326", *src_dst.bounds)` however this may need to be used outside of `rio_stac` OR to propose a change to `rio_stac` to address this issue.

**Comment by vincentsarago** [comment]
I just release rio-stac 0.7.0 with a `fix` for this.

There is now a `geom_densify_pts` option which will add points on each polygon edges to take care of the non-linear transformation. The option is **Optional** so you will need to set it on your code

**Comment by smohiudd** [comment]
Merged PR https://github.com/NASA-IMPACT/veda-data-pipelines/pull/324 into develop which seems to have fixed this problem - no more 404 errors or blurry tiles!



![Image](https://user-images.githubusercontent.com/34844565/230081415-07973a10-9130-4d46-83e1-76384ed5a443.png)

**Comment by j08lue** [comment]
Confirmed. Nice, @smohiudd et al!
