### ISSUE TITLE
Implement tests which can run locally

### ISSUE THREAD

**Issue by moradology** [NASA-IMPACT/veda-data-pipelines#247]
Airflow grants the ability to run tests locally with the help of https://github.com/aws/aws-mwaa-local-runner. We should have some simple tests that can be run before pushing and during CI, so this task includes writing simple testing of capabilities and updates to CI scripts as necessary to test our PRs automatically

**Comment by moradology** [comment]
Working through the instructions on the `aws-mwaa-local-runner` github, it appears that our use of ECS/fargate is going to require some extra work. In particular, we'll need to set up airflow aws connections if we want `AWS Operators` to work: https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html

**Comment by moradology** [comment]
I've moved this work back to `ready` so that we can resume work on this after discussions with the wider devseed team after the new year

**Comment by gadomski** [comment]
Closing as OBE, we're sunsetting this repo: https://github.com/NASA-IMPACT/veda-architecture/issues/322.
