### ISSUE TITLE
ADR about in-pipeline validation options

### ISSUE THREAD

**Issue by moradology** [NASA-IMPACT/veda-data-pipelines#248]
A common problem with ETL and data management pipelines is verification of data quality. It would be useful for us to be on the same page about how and when such validation strategies make sense. As an example, here's an integration which provides conventions for checkpoints, validations, and conditional retries: https://legacy.docs.greatexpectations.io/en/latest/guides/how_to_guides/validation/how_to_run_a_checkpoint_in_airflow.html

**Comment by moradology** [comment]
This might be a supplement to #246. Not sure

**Comment by ividito** [comment]
> This might be a supplement to #246. Not sure

Agreed, a few of the data validation tasks that are included in that issue's scope are:

- are the sample data files accessible by our services
- are the sample data files cloud-optimized (where cogify is set to false)
- are the sample data files readable (correct format, no data errors)

I don't know that we've determined where those validations will "live", whether they're part of a public API or built into the ingestion process. The checkpoint doc you linked makes me think that we could potentially incorporate these checks into Airflow, as long as we figured out a good way to return the results to the user.

**Comment by moradology** [comment]
If we have a solid way to ID (a hash maybe?) an ingest definition and we store statuses which capture details like that in a dynamo db I'm thinking the best strategy here might just be to provide a simple UI that reports on statuses we store

**Comment by j08lue** [comment]
@slesaad this is the ADR ticket you proposed, I think.
