### ISSUE TITLE
Update dev env for airflow

### ISSUE THREAD

**Issue by moradology** [NASA-IMPACT/veda-data-pipelines#250]
After moving to airflow, the structure of our project should be nearly identical to what it is now. This means a deployment directory with terraform or cdk for bringing up AWS resources as well as a DAGs directory which corresponds roughly to the lambda handler directory we currently have.

- [x] Airflow code mirrors structure in `main`
- [x] Scripts to deploy/ingest/etc all updated to work with airflow
- [x] Documentation updated to note important changes

**Comment by j08lue** [comment]
Closed with https://github.com/NASA-IMPACT/veda-data-pipelines/pull/256
