### ISSUE TITLE
Design metadata for Zarr datasets

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#263]
For COGs, it's straight forward that we have collections and items (although admittedly it's sometimes hard to define the scope of a particular collection)

For Zarr, since all data is accessed via a consolidated metadata file, individual items don't really make sense (since data is stored in "chunks" representing a specific chunk of data from the different dimensions of the dataset.

There is prior art in MS planetary computing and presumably pangeo forge catalog on how to catalog this data that we should follow.

https://discourse.pangeo.io/t/stac-and-earth-systems-datasets/1472/15

**Comment by slesaad** [comment]
I've started this doc here (still a WIP): https://docs.google.com/document/d/1XVVd0x1yILNVpHF_T7tRJK0Ucoj22pqmMOvThFEm72U/edit#

**Comment by slesaad** [comment]
Updated the document with more details and a recommendation for cataloging zarr in STAC using planetary computer reference. The document is still kind of informal. @anayeaye could you review it, so when we go decide on a strategy, I'll create a new document.
