### ISSUE TITLE
Make inventory for completing datasets from COVID dashboard

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#274]
For completing our PI objective https://github.com/NASA-IMPACT/veda-architecture/issues/161 to complete datasets from the COVID Dashboard that are only partially represented in the VEDA catalog, we need to first get an overview of the datasets and the amount of missing data.

## Acceptance Criteria

- [x] #275
- [x] Created issues for completing the datasets

**Comment by slesaad** [comment]
Here's the API for datasets being used by COVID19: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/datasets

**Comment by anayeaye** [comment]
I pulled some h[igh level object counts in the UAH and MCP buckets](https://docs.google.com/spreadsheets/d/1BP5S1eBwmOfEyiKGonDQfUyHMU3rutmI5fTrMJthGPc/edit#gid=917874775) for our veda data storage estimate ([architecture issue 173](https://github.com/NASA-IMPACT/veda-architecture/issues/173)) that might be useful for identifying gaps in the inventory.

**Comment by smohiudd** [comment]
Thanks Alex, your list was really helpful. I'm tracking the datasets in this ticket: https://github.com/NASA-IMPACT/veda-data-pipelines/issues/275

**Comment by j08lue** [comment]
Inventory completed. See linked tickts.
