### ISSUE TITLE
Add new GEOGLAM item for January 2023

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#281]
We received a new file to add to the GEOGLAM collection. I already re-built the overviews and verified that the file loads fine (in QGIS).

Please copy the file from here: https://drive.google.com/file/d/1gsrI0Lm8rhphtN1-C72If-1EIEey8iq7/view

## Acceptance criteria

- [ ] January 2023 data is available in the Dashboard and renders nicely https://www.earthdata.nasa.gov/dashboard/agriculture/datasets/geoglam/explore?datetime=2022-11-01T00%3A00%3A00.000Z&position=24.0775%7C40.5713%7C2.93

**Comment by sbquinlan** [comment]
requested access to the dropbox. So I think I kind of get this now. I'm just supposed to run this script and upload a new item into the collection? Do we do all of that updating manually for all collections?

**Comment by smohiudd** [comment]
@sbquinlan the new file should be added to `s3://veda-data-store-staging/geoglam/` and then follow the documentation [here](https://github.com/NASA-IMPACT/veda-data-pipelines/blob/main/OPERATING.md) about "Ingesting items to a collection".

**Comment by anayeaye** [comment]
I have uploaded the file to `s3://veda-data-store-staging/geoglam/CropMonitor_2023_01_28.tif`. I have not verified the file itself, though.

**Comment by j08lue** [comment]
I verified and re-cloud-optimized the file when I got it.

Looks fine in preview and stats
* https://staging-raster.delta-backend.com/cog/preview?url=s3%3A%2F%2Fveda-data-store-staging%2Fgeoglam%2FCropMonitor_2023_01_28.tif
* https://staging-raster.delta-backend.com/cog/statistics?url=s3%3A%2F%2Fveda-data-store-staging%2Fgeoglam%2FCropMonitor_2023_01_28.tif

**Comment by sbquinlan** [comment]
https://staging-stac.delta-backend.com/collections/geoglam Jan 2023 in there. I think we're good here? Feel free to reopen if I'm wrong

**Comment by j08lue** [comment]
Nice! Looks right in the Dashboard, too:

![image](https://user-images.githubusercontent.com/3404817/220845043-524a19f6-54cf-4913-ba35-3d61df1037ff.png)

https://www.earthdata.nasa.gov/dashboard/agriculture/datasets/geoglam/explore?position=15.05%7C13.9525%7C2.42&datetime=2023-01-01T00%3A00%3A00.000Z
