### ISSUE TITLE
Add COVID Recovery Proxy Map dataset

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-pipelines#282]
## What
Ingest dataset is stored in: `s3://covid-eo-data/rpm/`
Example `s3://covid-eo-data/rpm/rpm-ny.cog.tif` `s3://covid-eo-data/rpm/rpm-<spotlightId>.cog.tif`

In the same bucket, raw data should not be ingested exclude files in source data directory `covid-eo-data/source-data/`

## Collection info
  - id: recovery-proxy-maps-covid-19
  - title: Recovery Proxy Maps
  - description: Recovery Proxy Maps show areas with the greatest increase in car activity shaded in orange. Darker orange indicates areas of greater change
  - license: CC0-1.0
  - temporal interval: 2020 full year (use Jan thru December 2020 for all items)
  - is periodic = False
  - dashboard time density is Null, do not include it

## Notes
- [Covid 19 dashboard data migration discussion doc](https://docs.google.com/document/d/1xiBf9Awo8DShrRJhMZcfhunchEynUTA52xHzYZQZ0HE/edit#)
- These tiffs are for spotlight areas and not associated with specific covid-19 discoveries, only locations
- The items should represent the entire year of 2020, that is as precise as we can be
- Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md to create collection and ingest items

## AC
- [x] RPM data are copied to veda-data-store-staging
- [x] Recovery Proxy Maps ingested into VEDA
- [x] Notify @danielfdsilva and @nerik that the recovery proxy maps are available in VEDA

**Comment by moradology** [comment]
Without further direction, we won't be able to ingest this data. The processed cogs appear to lack dates: [rpm-be.cog.tif](https://s3.console.aws.amazon.com/s3/object/covid-eo-data?region=us-east-1&prefix=rpm/rpm-be.cog.tif). The `source` tifs appear to have 4 dates (our convention is to work with 1 date in periodic datasets though 2 is likely the most we can accommodate via standard stac datetime fields)

**Comment by smohiudd** [comment]
PR created in veda-config: https://github.com/NASA-IMPACT/veda-config/pull/282

**Comment by gadomski** [comment]
Closing as Done on the project board.
