### ISSUE TITLE
Add COVID Slowdown Proxy Map Dataset

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-pipelines#283]
Dataset is stored in: `s3://covid-eo-data/slowdown_proxy_map/`

- [x] Gather STAC collection metadata

  - id: slowdown-proxy-covid-19-changing-landscapes *open to improvent
  - title: Slowdown Proxy Maps
  - description: Slowdown Proxy Maps show areas with the greatest reduction in car activity shaded in blue. Darker blues indicate areas of greater change.
  - license: CC0-1.0
  - temporal interval: 2020-01-01T00:00:00Z to 2020-12-31T23:59:59Z
  - dashboard:is_periodic False
  - do not set dashboard time density

## Notes

- There are multiple dates in some filenames and no dates in others. For the VEDA collection, create a stac item for each `.tif` in `covid-eo-data/slowdown_proxy_map/ ` and use start_time = `2020-01-01T00:00:00Z` and end_datetime-`2020-12-31T23:59:59Z` for every item. This is as precise as we can be with the info we have.
- The most important files are la.tif and sf.tif which support the changing landscapes discovery, if other files throw formatting errors/cause problems they can be skipped with an explantion of why in this ticket.
- [covid-19 migration wrap up document](https://docs.google.com/document/d/1xiBf9Awo8DShrRJhMZcfhunchEynUTA52xHzYZQZ0HE/edit#)
- This collection replaces static content in the [Covid-19 Changing Landscapes discovery](https://github.com/NASA-IMPACT/veda-config/pull/229)

- [x] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md to create collection and ingest items
- [x] Once approved, merge and close.

## Acceptance criteria
- [x] SPM data are copied to veda-data-store-staging
- [x] Notify @danielfdsilva and @nerik that the slowdown data collection for the Covid-19 Changing Landscapes stores has been published

**Comment by moradology** [comment]
To ingest this data we'll need some information about its collection-level data and some guidance on which of the 4 available dates in cog names are relevant for the corresponding stac item (e.g. one cog is named Aichi_S1_TA112_SPM_20200109-20200214_20200426-20200508_th-0.35.cog.tif)

**Comment by smohiudd** [comment]
The collection and items are in dev: https://dev-stac.delta-backend.com/collections/slowdown-proxy-covid-19-changing-landscapes.

@danielfdsilva do you only need this dataset for the the changing landscapes [discovery](https://github.com/NASA-IMPACT/veda-config/pull/229)? I'm assuming this isn't going to be its own dataset

**Comment by danielfdsilva** [comment]
@smohiudd for it to be used in a discovery it needs to be added as a normal dataset. Would that be a problem?

**Comment by smohiudd** [comment]
@danielfdsilva no shouldn't be a problem. I'll work on getting dataset in veda-config and into the staging api.

**Comment by smohiudd** [comment]
PR created in veda-config: https://github.com/NASA-IMPACT/veda-config/pull/282

**Comment by gadomski** [comment]
Closing as Done on the project board.
