### ISSUE TITLE
Add COVID Water PZD Dataset

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-pipelines#286]
Photic Zone Depth Anomaly (PZD)
Dataset is stored in: `s3://covid-eo-data/pzd_anomaly/` dates are in file name. 
These data are not specifically associated with a covid-19 dashboard story.

## STAC collection metadata
  - id: pzd-anomaly-covid-19
  - title: Photic Zone Depth Anomaly
  - description: Photic zone depth (PZD) is the depth at which only 1% of the surface irradiation remains, and is an indicator of water clarity. PZD is impacted by concentrations of chlorophyll-a, suspended solids, and CDOM. Redder colors indicate increased water clarity. Bluer colors indicate decreased water clarity. White areas indicate no change.
  - license: CC0-1.0
  - temporal interval:
  - is periodic = False (there are gaps between dates)
  - the dashboard time density: day

## Notes
- [Static covid-19 PZD data](https://github.com/NASA-IMPACT/covid-api/blob/develop/covid_api/db/static/datasets/water-pzd.json)
- These data are not specifically associated with a covid-19 dashboard story
- Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md

## AC
- [x] pzd data migrated to veda-data-store-staging
- [x] pzd data collection and items published to dev and staging STAC
- [x] Notify @danielfdsilva and @nerik that the covid-19 water quality photic zone depth anomaly (spotlight) data are ingested

**Comment by gadomski** [comment]
Closing as Done on the project board.
