### ISSUE TITLE
Add COVID Togo Agriculture Dataset

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-pipelines#288]
Dataset is stored in: s3://covid-eo-data/Togo/
This collection contains only one COG: `s3://covid-eo-data/Togo/togo_cropland_v7-1_cog_v2.tif`

- [x] Verify that files are valid COGs (e.g. with [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation))
- [x] Gather STAC collection metadata

  - id: togo-agriculture-covid-19
  - title: Togo Agriculture
  - description: NASA Harvest developed a national-level, satellite-derived cropland map for Togo at 10-meter resolution within a 10-day timeframe using data from the European Space Agency’s Copernicus Sentinel 2 satellite, the NASA-USGS Landsat satellites, and with data from commercial partner Planet Inc. Dark purple colors indicate lower probability of cropland while lighter yellow colors indicate higher probability of cropland within each pixel.
  - license: CC0-1.0
  - temporal interval: 2020 full year
  - dashboard is periodic = False
  - the dashboard time density: null

## Notes
- [covid-19 migration wrap up document](https://docs.google.com/document/d/1xiBf9Awo8DShrRJhMZcfhunchEynUTA52xHzYZQZ0HE/edit#)

## AC
- [x] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md
- [x] Togo Agriculture data migrated to veda-data-store-staging
- [x] Togo Agriculture collection and items published to dev and staging STAC
- [x] Once approved, merge and close.
- [x] Notify @danielfdsilva and @nerik that the agriculture dataset for the Togo spotlight area has been migrated to VEDA

**Comment by moradology** [comment]
Require some input from above about the contents of the STAC collection

**Comment by gadomski** [comment]
Closing as Done on the project board.
