### ISSUE TITLE
Add selected Landsat scenes for two Antarctic glaciers

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#289]
For a discovery on two Antarctic glaciers, we need illustrating data.

Our first priority is to create two collections of selected, cloud-free Landsat 7-9 surface reflectance from 2000-2019 - one for each of the study areas - linking directly to ARCO Landsat COGs in ASDI https://registry.opendata.aws/usgs-landsat/. 

We may be able to do the search on their STAC and then import the relevant STAC items more or less directly into our catalog. https://landsatlook.usgs.gov/stac-server/collections/landsat-c2l2-sr/items

The glaciers are Thwaites Glacier and Pine Island Glacier. I can provide AOIs for both.

If possible, we can have one (or a few) paths/rows for each AOI that cover the area, so users can quickly browse and stack the data into a pixel-aligned timeseries without need for reprojection / mosaicing.

## Acceptance Criteria

- [x] We have two new collections, one for each of the glacier, with a pre-filtered stack of informative Landsat imagery

**Comment by j08lue** [comment]
Snippet from Planetary Computer that we can perhaps adapt for searching the LandsatLook STAC.

```python
from pystac_client import Client
import planetary_computer as pc

# Search against the Planetary Computer STAC API
catalog = Client.open(
  "https://planetarycomputer.microsoft.com/api/stac/v1"
)

# Define your area of interest
aoi = {
  "type": "Polygon",
  "coordinates": [
    [
      [-104.0007825990597, -75.20950788031237],
      [-98.82898308022193, -75.20950788031237],
      [-98.82898308022193, -74.43306685690168],
      [-104.0007825990597, -74.43306685690168],
      [-104.0007825990597, -75.20950788031237]
    ]
  ]
}

# Define your temporal range
daterange = {"interval": ["2001-11-30T00:00:00Z", "2023-02-07T23:59:59Z"]}

# Define your search with CQL2 syntax
search = catalog.search(filter_lang="cql2-json", filter={
  "op": "and",
  "args": [
    {"op": "s_intersects", "args": [{"property": "geometry"}, aoi]},
    {"op": "anyinteracts", "args": [{"property": "datetime"}, daterange]},
    {"op": "=", "args": [{"property": "collection"}, "landsat-c2-l2"]},
    {"op": "<=", "args": [{"property": "eo:cloud_cover"}, 50]},
    {"op": "=", "args": [{"property": "landsat:wrs_row"}, "113"]},
    {"op": "=", "args": [{"property": "landsat:wrs_path"}, "001"]}
  ]
})

# Grab the first item from the search results and sign the assets
first_item = next(search.get_items())
pc.sign_item(first_item).assets
```

**Comment by j08lue** [comment]
Pls note: one path/row for each area would probably suffice and an ingest by hand, too (no new pipeline work required for this tone).

**Comment by j08lue** [comment]
Thwaites Outlet

```json
{
"type": "FeatureCollection",
"name": "ThwaitesOutlet",
"features": [
{ "type": "Feature", "properties": { "id": 1, "Name": "ThwaitesOutlet" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -105.907941600669091, -74.619307279354686 ], [ -105.665498869260688, -75.53218074388603 ], [ -108.525925278513583, -75.667983860840124 ], [ -108.263445929787039, -74.702957876852849 ], [ -105.907941600669091, -74.619307279354686 ] ] ] } }
]
}
```

## Pine Island Outlet

```json
{
"type": "FeatureCollection",
"name": "PineIslandOutlet",
"features": [
{ "type": "Feature", "properties": { "id": 1, "Name": "PineIslandOutlet" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ -97.606988720812978, -74.67132766742013 ], [ -99.039703783064581, -75.828946600171534 ], [ -103.503101194845897, -75.426063575639915 ], [ -101.388858017502287, -74.335331564382116 ], [ -97.606988720812978, -74.67132766742013 ] ] ] } }
]
}

```

**Comment by j08lue** [comment]
This is very simple, but just to document this somewhere:

### What I have done so far:
1. Find a nice Landsat path/row for each of the AOIs (QGIS)
1. Use the Planetary Computer STAC search to find Landsat scenes that have <=20% cloud cover for each of the two path/row tiles
1. Use that list and check that the same scenes and IDs exist in the LandsatLook STAC API for the ASDI repo https://landsatlook.usgs.gov/stac-server - they are all there.
1. Have a look at the LandsatLook STAC entries - turns out they do not have the S3 URLs as asset hrefs. So we need to massage them into our format a bit, before importing them into our catalog.

### Next steps:
1. Code up the transformation of the item metadata
2. Generate the STAC metadata for the items
3. Load that into our catalog
4. Test
5. Celebrate

**Comment by anayeaye** [comment]
Quick note here on the STAC metadata--I see what you mean, the s3 URIs are available but those hrefs are nested in an alternative link that I'm not sure our system will parse. There is an additional issue we need to address which is that the data need to be accessed as requester pays which is not the default configuration in our TiTiler. It may be a simple change but we need to look into whether or not adding that environment variable to our TiTiler has any impact on other assets we tile today.

`AWS_REQUEST_PAYER=requester gdalinfo /vsis3/usgs-landsat/collection02/level-2/standard/oli-tirs/2023/001/113/LC09_L2SR_001113_20230202_20230204_02_T2/LC09_L2SR_001113_20230202_20230204_02_T2_SR_B1.TIF`

**Comment by j08lue** [comment]
@anayeaye I added collections metadata in the [`feature/add-antarctic-glaciers-landsat`](https://github.com/NASA-IMPACT/veda-data-pipelines/tree/feature/add-antarctic-glaciers-landsat) branch.

**Comment by anayeaye** [comment]
I added a couple issues for the API modifications needed to support this dataset:

https://github.com/NASA-IMPACT/veda-backend/issues/158 is needed right away to allow the tiler to load data from a requester-pays bucket

https://github.com/NASA-IMPACT/veda-backend/issues/157 is for future nice-to-have work to prepare the tiler for other EarthDataCloud datasets that use the stac alternate-assets extension.

**Comment by j08lue** [comment]
```python
def get_fixed_item_dict(item):
    item_dict = item.to_dict()

    for asset in item_dict["assets"].values():
        if "alternate" in asset:
            asset["href"] = asset["alternate"]["s3"]["href"]
            del asset["alternate"]
            del asset
    item_dict["stac_extensions"] = [link for link in item_dict["stac_extensions"] if "alternate-assets" not in link]
    return item_dict
```

**Comment by moradology** [comment]
I've assembled and updated all the fields as appropriate but I'm running into a frustrating limitation of one of VEDA's decisions around assets: `item_assets` on collections *must* include (this is enforced by our ingestor) a `cog_default` asset and its description. The only problem is that this requirement doesn't make sense for landsat. Here are what I believe the correct collections and a sample item: https://gist.github.com/moradology/6f8fe1ad21aeb8a1bf6600c6c761be42

**Comment by moradology** [comment]
https://dev-stac.delta-backend.com/collections/landsat-c2l2-sr-antarctic-glaciers-thwaites/items
https://dev-stac.delta-backend.com/collections/landsat-c2l2-sr-antarctic-glaciers-pine-island/items

Adding to staging now

**Comment by j08lue** [comment]
Great, @moradology, thank you!

I can see the dev raster API can access the assets fine, e.g. https://dev-raster.delta-backend.com/cog/validate?url=s3://usgs-landsat/collection02/level-2/standard/oli-tirs/2022/005/113/LC08_L2SR_005113_20221220_20221227_02_T2/LC08_L2SR_005113_20221220_20221227_02_T2_SR_B4.TIF

I will pass this on to the ESA people and investigate how to create TiTiler links that make Natural Color composites.

Planetary Computer does it like this, for example:

https://planetarycomputer.microsoft.com/api/data/v1/item/tiles/WebMercatorQuad/8/60/79@2x?collection=landsat-c2-l2&item=LC09_L2SP_031021_20230308_02_T1&assets=red&assets=green&assets=blue&color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55&nodata=0&format=png

**Comment by j08lue** [comment]
Heureka - this is the equivalent for our tiler and it works:

https://dev-raster.delta-backend.com/stac/tiles/WebMercatorQuad/11/443/1674@2x?collection=landsat-c2l2-sr-antarctic-glaciers-thwaites&item=LC08_L2SR_001113_20230125_20230208_02_T2_SR&assets=red&assets=green&assets=blue&color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55&nodata=0&format=png

**Comment by moradology** [comment]
Hey, no problem. I assume that the window mixup implies that the items should be ingested again but associated with the opposite collection? Should be a quick fix

**Comment by moradology** [comment]
OK! Collections: updated. Old items: deleted. New items: ingested.

**Comment by j08lue** [comment]
Thank you, @moradology!

I see the right items are now associated with the right collections and the date ranges are also correct.

https://dev-raster.delta-backend.com/stac/tiles/WebMercatorQuad/11/443/1674@2x?collection=landsat-c2l2-sr-antarctic-glaciers-pine-island&item=LC08_L2SR_001113_20230125_20230208_02_T2_SR&assets=red&assets=green&assets=blue&color_formula=gamma+RGB+2.7%2C+saturation+1.5%2C+sigmoidal+RGB+15+0.55&nodata=0&format=png

The only thing that is different from the collection metadata I posted above is the **bounding boxes**. Did you compute them or use the ones I provided? If that is a single remaining mix-up, would you mind swapping this one piece of information between the two collections? Then everything should be 💯 .

https://dev-stac.delta-backend.com/collections/landsat-c2l2-sr-antarctic-glaciers-pine-island
https://dev-stac.delta-backend.com/collections/landsat-c2l2-sr-antarctic-glaciers-thwaites

**Comment by moradology** [comment]
I think things look good now (I also removed the bbox numbers from their quotes as i think these should be numbers)

**Comment by anayeaye** [comment]
I have one request to update the collection documents (not the ingested items): Because these two collections group items from multiple Landsat missions, I think we should make this fact and the reasoning a bit more obvious in the collection description. Right now we know these are multi mission/multi instrument collections but we could prevent future confusion and help our future selves out.

**Collection titles and description**
title: Selected Landsat Surface Reflectance Scenes for Thwaites Glacier
current description: Selected low-cloud-cover Landsat Collection-2 Level-2 Surface Reflectance scenes covering Thwaites Glacier

Ideas for updated description
Selected Landsat 7 through 9 Surface Reflectance Scenes for Thwaites Glacier
current description: Selected low-cloud-cover Landsat Collection-2 Level-2 Surface Reflectance scenes covering Thwaites Glacier. Products from multiple missions and instruments are combined in this single collection for the purpose of visualizing RGB images. Note that the full item records are not interchangeable across instruments for purposes other than visualization and that the assets available are not the same for each instrument.


**Item_assets object**
For this, I think we would be safest just paring the object to down to just the red, green, blue assets that are the purpose of the multi mission collection (maybe keep thumbs and metadata? just whatever can be reasonably described for all items in the collection). In the shortened asset list we'd need to update asset descriptions to reflect all the possible definitions. I think the center wavelength will probably be stable across instruments but we may want to use a combo description like this, for example:

description: Collection 2 Level-2 Red Band Surface Reflectance (ETM Band 3; OLI,TIRS Band 4)
