### ISSUE TITLE
Create houston-lst-day diff dataset/ ingest and publish

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data-pipelines#299]
# PI Objective

# Description
Copying over a conversation from slack:

> Yaitza wants another spatial plot added at the top of the [EJ Urban Heat] story to drive home a punchline. We’re going to work on a comparison of 2018 Socioeconomic SVI and temperature difference from 2000-2009 and 2010-2019. ...
Yaitza recommended we hold publishing the story until that visual is in place.

# Acceptance Criteria
- [x] Created a new cog for the temperature difference
- [x] Ingested and published a new collection with the new cog to dev stac
- [x] Ingested and published a new collection with the new cog to staging stac

**Comment by slesaad** [comment]
Creating a new cog was easy enough using the `gdal_calc.py` command; the cog has been uploaded to `climatedashboard-data/houston/`

Next up: publishing

**Comment by slesaad** [comment]
Published to dev and staging, and is being used in the [Urban Heat EJ story](https://deploy-preview-193--visex.netlify.app/environmental-justice/discoveries/urban-heating)

Input to `/dataset/publish`:

```json
{
  "collection": "houston-lst-diff",
  "title": "Houston LST (Diff)",
  "description": "Changes in decadally averaged land surface temperature (LST, daytime) in the Houston metro area. The higher the value, the larger the increase.",
  "license": "CC0-1.0",
  "is_periodic": false,
  "time_density": null,
  "spatial_extent": {
    "xmax": -94.00,
    "ymax": 31.00,
    "xmin": -97.00,
    "ymin": 28.00
  },
  "temporal_extent": {
    "startdate": "2000-01-01T00:00:00Z",
    "enddate": "2019-12-31T23:59:59Z"
  },
  "sample_files": [
    "s3://climatedashboard-data/houston/houston-lst-diff_2000_2019.tif"
  ],
  "discovery_items": [
    {
      "discovery": "s3",
      "cogify": false,
      "upload": true,
      "dry_run": false,
      "prefix": "houston",
      "bucket": "climatedashboard-data",
      "filename_regex": "^(.*)houston-lst-diff(.*).tif$",
      "datetime_range": "year"
    }
  ]
}

```

**Comment by hanbyul-here** [comment]
The discovery using this dataset is published:  https://www.earthdata.nasa.gov/dashboard/environmental-justice/discoveries/urban-heating, but the dataset often fails to load. (It is not only lst day diff dataset problem, but just leaving a comment here.) Considering we don't observe this problem with other datasets, the problem is unlikely on the front-end side. Can you offer some insights on this issue @anayeaye ?
