### ISSUE TITLE
Add Fire Discovery datasets on Thomas Fire

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#305]
- [x] Identify the point of contact and ensure someone is providing them updates: 
- [x] Data provider has read [guidelines on data preparation](https://github.com/NASA-IMPACT/veda-workflows-api/blob/main/how-to.md#prepare-the-data)
- [x] Identify data location:
   1. s3://veda-data-store-staging/EIS/COG/Fire-Hydro/thomas_fire_barc_201712.cog.tiff
   2. s3://veda-data-store-staging/EIS/COG/Fire-Hydro/thomas_fire_frpmax_201712.cog.tiff
- [x] Number of items: 2
- [x] Verify that files are valid COGs (e.g. with [`rio cogeo validate`](https://cogeotiff.github.io/rio-cogeo/Is_it_a_COG/#3-cog-validation))
   - ✅ https://staging-raster.delta-backend.com/cog/validate?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/thomas_fire_barc_201712.cog.tiff
   - ✅  https://staging-raster.delta-backend.com/cog/validate?url=s3://veda-data-store-staging/EIS/COG/Fire-Hydro/thomas_fire_frpmax_201712.cog.tiff
- [x] Gather STAC collection metadata

  - id:
  - title:
  - description:
  - license:
  - temporal interval:
  - whether it is periodic on the dashboard (periodic = regular time series of layers without gaps):
  - the dashboard time density:

```json
{
  "collection": "barc-thomasfire",
  "title": "barc-thomasfire",
  "description": "Burn Area Reflectance Classification (BARC) from the Burned Area Emergency Response (BAER) program for Thomas fire, 2017",
  "license": "CC0-1.0",
  "is_periodic": false,
  "time_density": null,
  "spatial_extent": {
    "xmin": -119.73,
    "ymin": 34.19,
    "xmax": -118.88,
    "ymax": 34.73
  },
  "temporal_extent": {
    "startdate": "2017-12-01T00:00:00Z",
    "enddate": "2017-12-01T00:00:00Z"
  },
  "sample_files": [
    "s3://veda-data-store-staging/EIS/COG/Fire-Hydro/thomas_fire_barc.cog.tiff"
  ],
  "discovery_items": [
    {
      "discovery": "s3",
      "cogify": false,
      "upload": false,
      "dry_run": false,
      "prefix": "EIS/COG/Fire-Hydro/",
      "bucket": "veda-data-store-staging",
      "filename_regex": "(.*)common_part_of_filenames(.*).tif$",
      "datetime_range": "year/month/day"
    }
  ]
}
```

```json
{
  "collection": "frp-max-thomasfire",
  "title": "frp-max-thomasfire",
  "description": "Maximum Fire Radiative Power per 12hr fire line segment for Thomas fire",
  "license": "CC0-1.0",
  "is_periodic": false,
  "time_density": null,
  "spatial_extent": {
    "xmin": -119.73,
    "ymin": 34.19,
    "xmax": -118.88,
    "ymax": 34.73
  },
  "temporal_extent": {
    "startdate": "2017-12-01T00:00:00Z",
    "enddate": "2017-12-01T00:00:00Z"
  },
  "sample_files": [
    "s3://veda-data-store-staging/EIS/COG/Fire-Hydro/thomas_fire_frpmax.cog.tiff"
  ],
  "discovery_items": [
    {
      "discovery": "s3",
      "cogify": false,
      "upload": false,
      "dry_run": false,
      "prefix": "EIS/COG/Fire-Hydro/",
      "bucket": "veda-data-store-staging",
      "filename_regex": "(.*)common_part_of_filenames(.*).tif$",
      "datetime_range": "year/month/day"
    }
  ]
}
```

- [x] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md
- [ ] Open PR for publishing those datasets to the Staging API:
- [ ] Notify QA / move ticket to QA state
- [ ] Once approved, merge and close.

## Resources on metadata

If not already familiar with these conventions for generating STAC collection and item metadata:
       - Collections: https://github.com/NASA-IMPACT/delta-backend/issues/29 and STAC version 1.0 specification for collections
       - Items: https://github.com/NASA-IMPACT/delta-backend/issues/28 and STAC version 1.0 specification for items
       - NOTE: The delta-backend instructions are specific to datasets for the climate dashboard, however not all datasets are going to be a part of the visual layers for the dashboard so you can ignore the instructions that are specific to "dashboard" extension, "item_assets" in the collection and "cog_default" asset type in the item.

**Comment by slesaad** [comment]
These have been published to dev stac catalog and sent for review.
Once reviewed, they will be published to staging.

**Comment by slesaad** [comment]
The datasets are in staging, so closing this!
