### ISSUE TITLE
Add new GEOGLAM item for February 2023

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#308]
Same as #281, but for February.

Here is the file, already checked and fixed: https://drive.google.com/file/d/1qyr_1qBS8c_MCCn8JEiyxYCLxd8UfSqe/view

## Acceptance criteria

- [x] February 2023 data is available in the Dashboard and renders nicely https://www.earthdata.nasa.gov/dashboard/agriculture/datasets/geoglam/explore?datetime=2022-11-01T00%3A00%3A00.000Z&position=24.0775%7C40.5713%7C2.93

**Comment by moradology** [comment]
Looks like things are working: 

![Image](https://user-images.githubusercontent.com/1977405/224826945-c0cab5a4-6b29-4c21-b9d8-5bbf93676d05.png)
