### ISSUE TITLE
Urban heating Discovery/houston-* intermittent failures

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data-pipelines#315]
# What
Maps in urban heating discovery are intermittently failing to load, see note:
https://github.com/NASA-IMPACT/veda-data-pipelines/issues/299#issuecomment-1464494004

# Notes
- The dev-stac-api and staging-stac-api versions of the land cover collection refer to different assets, the dev assets are newer

# AC
- [x] All maps in urban heating discovery load data

**Comment by slesaad** [comment]
Thanks for pointing out the issue @anayeaye !
I updated the staging catalog with the updated cogs.
I've loaded it in multiple browsers multiple times and they seem to load fine to me.
Hopefully, the intermittent failures don't happen anymore!

Closing this, for now, will reopen if we see failures in the future!
