### ISSUE TITLE
Ingest Volumetric Soil Moisture (sport-lis-vsm0-100cm-percentile)

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data-pipelines#323]
# What
Ingest Volumetric Soil Moisture dataset

## Data format and location
2 COGs already veda-data-store-staging. Each file should be a single band COG representing the single date in the filename.
Prefix `sport-lis-vsm0_100cm-percentile`
Keys to ingest:
- `s3://veda-data-store-staging/sport-lis-vsm0_100cm-percentile/sport_lis_vsm0-100cm_percentile_conus3km_float_wgs84_20160906.tif`
- `s3://veda-data-store-staging/sport-lis-vsm0_100cm-percentile/sport_lis_vsm0-100cm_percentile_conus3km_float_wgs84_20161129.tif`

Note that these were cogified manually with `gdal_translate gdal_translate -of COG -a_nodata 9999 -co COMPRESS=DEFLATE`. The valid range of values is 0-100.

### Point of contact
@freitagb 

## Collection 
Info for collection (add stac formatting; update extents after ingestion if needed)
```
{
    "collection": "sport-lis-vsm0_100cm-percentile",
    "description": "The NASA Short-term Prediction Research and Transition (SPoRT) Center has developed a Real-Time Land Information System (LIS). The Volumetric Soil Moisture product represents the actual moisture in a soil column from 0-100cm in depth.",
    "is_periodic": false,
    "license": "CC0-1.0",
    "spatial_extent":
    {
        "xmax": -67.07,
        "xmin": -124.94,
        "ymax": 52.93,
        "ymin": 25.06
    },
    "temporal_extent":
    {
        "enddate": "2016-11-29T23:59:59Z",
        "startdate": "2016-09-06T00:00:00Z"
    },
    "time_density": null,
    "title": "0-100 cm Volumetric Soil Moisture (%)"
}
```

## Supporting info for dashboard config
Expected appearance
![20161129_test](https://user-images.githubusercontent.com/3386265/228042618-3ac1f35c-09a8-42d3-9bc2-eba51a84fea6.png)

**Valid pixel range is 0 to 100**

**Thematic area**
EIS-FIRE

**Text for dashboard config**
[SPoRT-LIS_writeupForVEDA.docx](https://github.com/NASA-IMPACT/veda-data-pipelines/files/11082186/SPoRT-LIS_writeupForVEDA.docx)

**colormap**
Ask @freitagb for custom 3 part colormap notes, try this `RdYlBu_r` for initial configuration (we should see red in the relatively drier soil of the burned area)

## AC
- [ ] data ingested to dev database
- [ ] data ingested to staging
- [ ] at a minimum a PR submitted to veda-config to demo the dataset in the dashboard
- [ ] only one pair of COGs is stored in veda-data-store-staging (currently there are two versions of each file, we should only keep the ones that have corresponding stac records)

**Comment by slesaad** [comment]
I had already started working on this! Here's the [draft PR](https://github.com/NASA-IMPACT/veda-config/pull/228) that I just created in veda-config

**Comment by slesaad** [comment]
This is done!
