### ISSUE TITLE
Confirm no issues with rio_stac 0.4.2 -> 0.7.0 upgrade

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-pipelines#325]
`rio_stac` will need to be upgraded to v 0.7.0 to address the issues we were having with stac bounding boxes as documented here: https://github.com/NASA-IMPACT/veda-data-pipelines/issues/235

Between version 0.4.2 and 0.7.0 ([changelog](https://github.com/developmentseed/rio-stac/blob/main/CHANGES.md)) there are some breaking changes that must be explored to confirm there are no impacts to the ingestion pipeline. The upgrade must also be applied to `veda-data-airflow` and `veda-pipeline-tasks`

### Acceptance Criteria:

- [x] confirm there are no impacts to existing pipeline OR impacts are addressed
- [x] rio_stac is updated in `veda-data-airflow` and `veda-data-pipeline`
- [x] upgrade is merged into `staging`

**Comment by smohiudd** [comment]
These are breaking changes between 0.4.2 and 0.7.0 and a description if they affect `build-stac`

**1. get dataset datetime from GDAL Raster Data Model**

In the handler event we have the option to pass `start_datetime` and `end_datetime`. If these are not included then the datetime is retrieved via regex from the filename. In v0.7.0 of rio_stac the datetime can also be retrieved using GDAL from the tiff itself via `("ACQUISITIONDATETIME", "IMAGERY")`. Since we are typically using regex for the datetime, this change won't have an impact. **No conflicts.**

**2. add eo extension support (eo:cloud_cover, eo:bands)**

`with_eo` is set to False in rio_stac 0.7.0 by default so this won't impact the current implementation of the pipeline. **No conflicts.**


**3. use auto by default for asset_media_type**

The asset media can be passed in the handler event as `asset_media_type` or else it will default to `"image/tiff; application=geotiff; profile=cloud-optimized"` so `auto` won't be triggered. 
```
 asset_media_type=(
                asset_media_type
                or "image/tiff; application=geotiff; profile=cloud-optimized"
            )
```
**No conflicts.**

**Comment by anayeaye** [comment]
Thanks for digging in to the docs into this and explaining why the changes are all safe for us!
