### ISSUE TITLE
Add MODIS active fire anomalies covid 19 collection

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-data-pipelines#327]
Dataset is stored in: `s3://covid-eo-data/standalone/fire-anomalies/`. Correct files follow `MODIS-AF_anomalies_USA_Y<YYYY>_M<month>_0.25-dashboard.tif` pattern, i.e. `MODIS-AF_anomalies_USA_Y2020_M3_0.25-dashboard.tif`. Ignore files that don’t have -dashboard.tif suffix.

- [x] Gather STAC collection metadata

  - id: modis-fire-anomalies-diff-covid-19-changing-landscapes *open to improvements
  - title: MODIS change in active fires compared to the baseline of 2012-2019
  - description: Change in active fires compared to the baseline of 2012-2019 from -10% to 10%
  - license: CC0-1.0
  - temporal interval: 2020
  - dashboard:is_periodic true
  - time density: month

## Notes
- Correct files follow `MODIS-AF_anomalies_USA_Y<YYYY>_M<month>_0.25-dashboard.tif` pattern, i.e. `MODIS-AF_anomalies_USA_Y2020_M3_0.25-dashboard.tif`. Ignore files that don’t have -dashboard.tif suffix. There are only around 8 files.
- This collection replaces static content in the [Covid-19 Changing Landscapes discovery](https://github.com/NASA-IMPACT/veda-config/pull/229)
- [covid-19 migration wrap up document](https://docs.google.com/document/d/1xiBf9Awo8DShrRJhMZcfhunchEynUTA52xHzYZQZ0HE/edit#)

- [x] Review and follow https://github.com/NASA-IMPACT/cloud-optimized-data-pipelines/blob/main/OPERATING.md to create collection and ingest items
- [x] Once approved, merge and close.

## Acceptance criteria
- [x] modis active fire anomalies data migrated to veda-data-store-staging
- [x] modis active fires collection published to dev and staging STAC 
- [x] Notify @danielfdsilva and @nerik that the modis fire anomalies collection for the Covid-19 Changing Landscapes stores has been published

**Comment by gadomski** [comment]
Closing as Done on the project board.
