### ISSUE TITLE
Update the secrets of the production environment in github

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [NASA-IMPACT/veda-data-pipelines#335]
We need to update the secrets (and maybe the environment variables) for the production environment in GitHub. The current secrets are place holders and we need to update them to ensure MWAA DAGs function as expected.

**Comment by amarouane-ABDELHAK** [comment]
Acceptance Criteria:

- [ ] github production environment secrets and variables are updated to the new values
- [ ] The GitHub Action that uses the updated secrets has been updated to reference the new values.
- [ ] The DAGs using these secret environment values are tested and are working as expected.

**Comment by gadomski** [comment]
@slesaad does this belong in https://github.com/NASA-IMPACT/veda-data-airflow/ instead of this repo? Feels that way...

**Comment by slesaad** [comment]
i think we can close this, it's irrelevant now :D
