### ISSUE TITLE
Categorical map rendering issue

### ISSUE THREAD

**Issue by vlulla** [NASA-IMPACT/veda-data-pipelines#339]
While trying to create a custom color map for landcover classes map of Bangladesh (in NASA-IMPACT/veda-config#134 ) we observe that the colors do not render for the whole map. However, as you zoom in you see the colors for the various classes get correctly rendered. And, once you zoom out the colors disappear again! Therefore, it appears to me that there might be some rendering issue related to zoom levels.

**Comment by j08lue** [comment]
We did something somewhere a while ago... Either way, the maps now render fine at all zoom levels:

https://www.earthdata.nasa.gov/dashboard/data-catalog/bangladesh-landcover-2001-2020/explore?position=89.1775%7C24.2462%7C9.8&datetime=2001-01-01T00%3A00%3A00.000Z

![Image](https://github.com/NASA-IMPACT/veda-data-pipelines/assets/3404817/e41379e1-771e-4255-ac68-37652d1a18fc)
