### ISSUE TITLE
Improve Issue Templates

### ISSUE THREAD

**Issue by jsignell** [NASA-IMPACT/veda-data-pipelines#341]
## PI Objective
- https://github.com/NASA-IMPACT/veda-architecture/issues/222

## Description
There are too many overlapping issue templates in this repo. Once we figure out exactly what we need from people (#340) we should update the issue templates to just have 2 options - "dataset request" and "not dataset request".

## Acceptance Criteria
- [ ] no more than 2 issue templates
- [ ] issue template(s) is in the new format so it is more beautiful and easier to use.

**Comment by gadomski** [comment]
Closing as OBE as we're sunsetting this repo: https://github.com/NASA-IMPACT/veda-architecture/issues/322
