### ISSUE TITLE
CMIP6 share sample COGs with team for validation

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#348]
## Acceptance criteria

- [x] Put sample files in S3
- [x] Shared links to S3 and code base with team

**Comment by SwordSaintLancelot** [comment]
I have uploaded the sample COGs into the S3 bucket and shared the source as well as the target S3 buckets.

**Comment by j08lue** [comment]
Pls post links here, too, just for the record. 🙏

**Comment by SwordSaintLancelot** [comment]
I have update the code base in the [same](https://github.com/NASA-IMPACT/CMIP6_transformation) repo. I have also changed the sample bucket to [climate-dashboard)([climatedashboard-data](https://s3.console.aws.amazon.com/s3/buckets/climatedashboard-data?region=us-east-1)). The folder name that I am saving the COGs is "sample-cmip6-20230522".
