### ISSUE TITLE
Ingest 2022 annual average OMI TR NO2

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#353]
We were asked to ingest the 2022 annual average OMI NO2 to complement the timeseries we already have (collection `OMI_trno2-COG`).

We need to figure out where this data file is and whether it needs to be converted.

## Acceptance criteria
- [x] We located the file and transformed it so it is ready to get ingested - @j08lue 
- [x] 2022 annual average is available in the VEDA Dashboard / STAC http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/collections/OMI_trno2-COG
- [x] NASA stakeholders have been informed (Manil, Zachary, Barry) - @j08lue has the contact
- [x] EO Dashboard team has been informed and we checked that the data also shows up there https://eodashboard.org/explore?x=0&y=-927662.42328&z=2.90689&poi=W8-N9&search=World%3A+Nitrogen+Dioxide+%28yearly%29

**Comment by j08lue** [comment]
The file to ingest is here: https://drive.google.com/drive/folders/18rsE919tG8PP9U0Kcy4VOS0Y9qj8aGUH 

Created by cloud-optimizing the original file (also included in that folder) with the command

```bash
rio cogeo create --cog-profile deflate --overview-resampling average original/OMI_trno2_0.10x0.10_2022_Col3_V4.tif cog/OMI_trno2_0.10x0.10_2022_Col3_V4.tif
```

The file name of the new file follows the same convention as we already have in the bucket (`s3://veda-data-store-staging/OMI_trno2-COG/`):

* `OMI_trno2_0.10x0.10_2021_Col3_V4.tif` - existing 2021 file
* `OMI_trno2_0.10x0.10_2022_Col3_V4.tif` - new 2022 file

**Comment by slesaad** [comment]
@j08lue this looks done? i checked the link in the EO dashboard!

**Comment by j08lue** [comment]
Right, good catch, thanks!
