### ISSUE TITLE
Automate the deployment of all GHGC/VEDA stacks using the Mono-repo

### ISSUE THREAD

**Issue by amarouane-ABDELHAK** [NASA-IMPACT/veda-data-pipelines#354]

**Comment by slesaad** [comment]
@amarouane-ABDELHAK this is the successor to this: https://github.com/NASA-IMPACT/veda-architecture/issues/245
please refer to that issue

**Comment by amarouane-ABDELHAK** [comment]
https://github.com/NASA-IMPACT/veda-deploy repo was created with submodules to different VEDA resources (auth, ingestor...)
The deployment will run a basic integration test to make sure the STAC and INGETOR API returns successful responses.


![Image](https://github.com/NASA-IMPACT/veda-data-pipelines/assets/33136280/c54d2bb8-df0d-4fb8-b554-7557641e247e)

Refer to README file for more info how to deploy the full stack

**Comment by gadomski** [comment]
@amarouane-ABDELHAK is this issue still active? Can we close it as complete since exists and is deploying things?

**Comment by amarouane-ABDELHAK** [comment]
This is done, it can be closed. Thank you
