### ISSUE TITLE
Remove/fix bad OMI collection

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#355]
In an attempt to close #353, I just tried to publish a new COG to add to the [OMI_trno2-COG STAC collection](http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/collections/OMI_trno2-COG) **in staging**, using this notebook: https://gist.github.com/j08lue/38e27e24fee779011cd8f2cbb49f8415

I kinda got it to work, but ran into the following issue:

1. The collection STAC validation failed - the collection name apparently has to be lowercase. So I submitted the request with a lowercase name - hoping it would somehow append to the right collection. It did not.
2. The ingestor created a new collection [omi_trno2-cog](http://veda-staging-stac-browser.s3-website-us-west-2.amazonaws.com/collections/omi_trno2-cog) (lowercase name) but it is somehow broken (see screenshot) - perhaps something to do with the bounding box / extent?

![image](https://github.com/NASA-IMPACT/veda-data-pipelines/assets/3404817/f84ac349-afa7-4342-a3b1-236a93ac9b4e)

```
Sorry, adding the data to the map failed.

Caused by:
    can't convert null to object
```

I need help fixing this, please:

## Acceptance criteria
- [x] Removed the lowercase `omi_trno2-cog` collection I erroneously created
- [x] Helped me ingest that single new item to the right collection
- [x] Open some tickets to fix the issue of existing uppercase collections when we do not allow that (anymore)

**Comment by anayeaye** [comment]
RE: the lower case collection.

There's a cascading delete on the collections in pgstac so I confirmed I had the right collection and then deleted it 
```
select count(*) item_count, collections.id
from items 
join collections on collections.id=items.collection
where collection = 'omi_trno2-cog'
group by collections.id, items.collection, collections."content"
order by collections.id, item_count;

--
item_count|id           |
----------+-------------+
         1|omi_trno2-cog|

--
select pgstac.delete_collection(collections.id)
from collections 
where id = 'omi_trno2-cog';
```

**Comment by slesaad** [comment]
Ingested the single item to the existing collection.
https://staging-stac.delta-backend.com/collections/OMI_trno2-COG/items/OMI_trno2_0.10x0.10_2022_Col3_V4
Basically by running this: https://github.com/NASA-IMPACT/veda-data-pipelines/blob/main/lambdas/build-stac/handler.py to create the stac record
And then using the `/ingestions` endpoint in veda-stac-ingestor staging api, to publish it

**Comment by slesaad** [comment]
Created this ticket too: https://github.com/NASA-IMPACT/veda-stac-ingestor/issues/67

**Comment by j08lue** [comment]
Excellent, thank you @slesaad and @anayeaye!
