### ISSUE TITLE
Review if CH4 plumes emission dataset is periodic

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/veda-data-pipelines#357]
The CH4 plumes emission dataset is marked as periodic but there are days without data.
We should review to understand if it is properly configured.

Related issues:
- https://github.com/NASA-IMPACT/veda-ui/issues/568
- https://github.com/NASA-IMPACT/veda-ui/pull/569#pullrequestreview-1504386485

cc @slesaad @j08lue

**Comment by slesaad** [comment]
@danielfdsilva good catch! we'll update the collection metadata
