### ISSUE TITLE
Add GEOGLAM item for June 2023

### ISSUE THREAD

**Issue by j08lue** [NASA-IMPACT/veda-data-pipelines#358]
Like #347 but for June - another GEOGLAM layer to ingest.

File link: https://drive.google.com/file/d/13Oenj50jpCAZcpZfM8me71XmZ-i4rGmS/view

(created with `rio cogeo create --overview-resampling mode <in.tif> <out.tif>` with `rio-cogeo=3.5.0`)

## Acceptance criteria

- [x] June 2023 layer is visible in the Dashboard

**Comment by j08lue** [comment]
Confirmed, thanks @kathrynberger!

<img width="786" alt="image" src="https://github.com/NASA-IMPACT/veda-data-pipelines/assets/3404817/7f00b5e3-266e-4795-96bf-5f2033624c6e">

**Comment by kathrynberger** [comment]
Thanks to you @ividito ☝️
