### ISSUE TITLE
cogification container not being pushed to aws' ECR

### ISSUE THREAD

**Issue by moradology** [NASA-IMPACT/veda-data-pipelines#359]
ECS tasks for the new `transfer+cogify` container have been added, but the actual container image appears to not be getting pushed.

**Comment by moradology** [comment]
Submitted to the wrong repo

**Comment by moradology** [comment]
Indeed, the wrong repo, but our issue tracker is set up here and not there so for now I will lodge the issue here.

**Comment by gadomski** [comment]
Yeah @moradology we're sunsetting this repo (https://github.com/NASA-IMPACT/veda-architecture/issues/322) so this should probably be transferred somewhere else.
