### ISSUE TITLE
COG Examples

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#43]
Acceptance criteria:
A docker image which produces a COG from any NetCDF4/HDF5 file using a user-provided config file

Tasks:
- [x] include configparser to parse configs
- [x] test with IMERG
- [ ] test with ERA5 file
- [ ] test with another example
- [ ] create a workflow to publish the Docker
- [ ] document how to use it

**Comment by slesaad** [comment]
raster-uploader!
