### ISSUE TITLE
Add dockerignore file

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#84]
When building docker images will save time, but need to do more research, suggestion from Sean

https://aws-blog.de/2020/10/speed-up-docker-image-building-with-the-cdk.html

**Comment by wildintellect** [comment]
Other tips to make Docker build better https://github.com/MAAP-Project/ZenHub/issues/506

**Comment by gadomski** [comment]
Closing as OBE as we're sunsetting this repo: https://github.com/NASA-IMPACT/veda-architecture/issues/322. Folks should re-open a similar issue on other repos if they don't have `.dockerignore` files.
