### ISSUE TITLE
Create a generic workflow for data publication

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#88]
I think we should have a generic workflow, not dataset specific, cdk code which can be used for:

1. Templating workflows
2. Perhaps setting up a workflow that might be triggered by any data in a `delivery` bucket to support user-added data to the API.

Scenario: 
1. (May only happen one time) User creates or updates collection STAC json in to s3://climatedashboard-data/delivery/<COLLECTION_NAME>/stac_collection.json
2. This triggers workflow to create or update the pgSTAC database with that collection record.
3. User puts COG(s) in s3://climatedashboard-data/delivery/<COLLECTION_NAME>/somedata_cog.tif.
4. This triggers a workflow which: validates the new or updated files as COGs and publishes those COGs as STAC items for the <COLLECTION_NAME>.

Additional tickets should be added to describe:
1. How do we authorize execution of these workflows? We want to make it easy for users to publish their own datasets, but maybe a simple IAM-based role for data curators is all that's needed.
1. How should the data and metadata be validated? Is validating the COG as a COG and the metadata as valid STAC sufficient?
2. How should ingestion errors be handled and communicated?
3. How would a user add the dataset to the dashboard?

**Comment by slesaad** [comment]
we have this already!
