### ISSUE TITLE
Add OMI NO2 SO2 db-write lambda security group to RDS security group inbound rules programmatically

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/veda-data-pipelines#99]
When I deployed `omi-no2-so2-cog-pipeline-staging`, since I was deploying to a new VPC, I found I had to add the security group of lambda which writes to the database to the database security groups permitted inbound groups. This should happen programmatically in the CDK code if possible.

**Comment by slesaad** [comment]
stale ticket
